DROP TRIGGER CNV$SUPPLNET_BI;
DROP SEQUENCE GEN_CNV$SUPPLNET_ID;
DROP INDEX CNV$SUPPLNET_IDX1;
DROP TABLE CNV$SUPPLNET;

DROP TRIGGER CNV$PENI_BI;
DROP SEQUENCE GEN_CNV$PENI_ID;
DROP INDEX CNV$PENI_IDX1;
DROP TABLE CNV$PENI;

DROP TRIGGER CNV$OPLATA_BI;
DROP SEQUENCE GEN_CNV$OPLATA_ID;
DROP INDEX CNV$OPLATA_IDX1;
DROP TABLE CNV$OPLATA;

DROP TRIGGER CNV$NACHOPL_BI;
DROP SEQUENCE GEN_CNV$NACHOPL_ID;
DROP INDEX CNV$NACHOPL_IDX1;
DROP TABLE CNV$NACHOPL;

DROP TRIGGER CNV$NACH_BI;
DROP SEQUENCE GEN_CNV$NACH_ID;
DROP INDEX CNV$NACH_IDX1;
DROP TABLE CNV$NACH;

DROP TRIGGER CNV$LGOTSUMMA_BI;
DROP SEQUENCE GEN_CNV$LGOTSUMMA_ID;
DROP INDEX CNV$LGOTSUMMA_IDX1;
DROP TABLE CNV$LGOTSUMMA;

DROP TRIGGER CNV$LCHARS_BI;
DROP SEQUENCE GEN_CNV$LCHARS_ID;
DROP INDEX CNV$LCHARS_IDX1;
DROP TABLE CNV$LCHARS;

DROP TRIGGER CNV$HADDCHAR_BI;
DROP SEQUENCE GEN_CNV$HADDCHAR_ID;
DROP TABLE CNV$HADDCHAR;

DROP TRIGGER CNV$GCOUNTER_BI;
DROP SEQUENCE GEN_CNV$GCOUNTER_ID;
DROP INDEX CNV$GCOUNTER_IDX1;
DROP TABLE CNV$GCOUNTER;

DROP TRIGGER CNV$EQUIPMENT_BI;
DROP SEQUENCE GEN_CNV$EQUIPMENT_ID;
DROP INDEX CNV$EQUIPMENT_IDX1;
DROP TABLE CNV$EQUIPMENT;

DROP TRIGGER CNV$DOGOVOR_BI;
DROP SEQUENCE GEN_CNV$DOGOVOR_ID;
DROP INDEX CNV$DOGOVOR_IDX1;
DROP TABLE CNV$DOGOVOR;

DROP TRIGGER CNV$CNTRSIND_BI;
DROP SEQUENCE GEN_CNV$CNTRSIND_ID;
DROP INDEX CNV$CNTRSIND_IDX1;
DROP TABLE CNV$CNTRSIND;

DROP TRIGGER CNV$COUNTERS_BI;
DROP SEQUENCE GEN_CNV$COUNTERS_ID;
DROP INDEX CNV$COUNTERS_IDX1;
DROP INDEX CNV$COUNTERS_IDX2;
DROP TABLE CNV$COUNTERS;

DROP TRIGGER CNV$CITYZENLGOTA_BI;
DROP SEQUENCE GEN_CNV$CITYZENLGOTA_ID;
DROP INDEX CNV$CITYZENLGOTA_IDX1;
DROP TABLE CNV$CITYZENLGOTA;

DROP TRIGGER CNV$CITIZENMIGRATION_BI;
DROP SEQUENCE GEN_CNV$CITIZENMIGRATION_ID;
DROP INDEX CNV$CITIZENMIGRATION_IDX1;
DROP TABLE CNV$CITIZENMIGRATION;

DROP TRIGGER CNV$CITIZENS_BI;
DROP SEQUENCE GEN_CNV$CITIZENS_ID;
DROP INDEX CNV$CITIZENS_IDX1;
DROP TABLE CNV$CITIZENS;

DROP TRIGGER CNV$CHARVALS_BI;
DROP SEQUENCE GEN_CNV$CHARVALS_ID;
DROP TABLE CNV$CHARVALS;

DROP TRIGGER CNV$CHARSHOUSES_BI;
DROP SEQUENCE GEN_CNV$CHARSHOUSES_ID;
DROP INDEX CNV$CHARSHOUSES_IDX1;
DROP TABLE CNV$CHARSHOUSES;

DROP TRIGGER CNV$CHARS_BI;
DROP SEQUENCE GEN_CNV$CHARS_ID;
DROP INDEX CNV$CHARS_IDX1;
DROP TABLE CNV$CHARS;

DROP TRIGGER CNV$CHARLST_BI;
DROP SEQUENCE GEN_CNV$CHARLST_ID;
DROP INDEX CNV$CHARLST_IDX1;
DROP TABLE CNV$CHARLST;

DROP TRIGGER CNV$AADDCHAR_BI;
DROP SEQUENCE GEN_CNV$AADDCHAR_ID;
DROP INDEX CNV$AADDCHAR_IDX1;
DROP TABLE CNV$AADDCHAR;

DROP TRIGGER CNV$ABONENT_BI;
DROP SEQUENCE GEN_CNV$ABONENT_ID;
DROP INDEX CNV$ABONENT_IDX1;
DROP INDEX CNV$ABONENT_IDX2;
DROP TABLE CNV$ABONENT;

DROP INDEX CNV$DOCUMENTNUMERATORTABLE_IDX1;
DROP TABLE CNV$DOCUMENTNUMERATORTABLE;

