#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using aConverterClassLibrary.RecordsDataAccessORM;

namespace aConverterClassLibrary.RecordsDataAccessORM	
{
	public partial class BALANCESLIST
	{
		private int _bALANCE_KOD;
		public virtual int BALANCE_KOD
		{
			get
			{
				return this._bALANCE_KOD;
			}
			set
			{
				this._bALANCE_KOD = value;
			}
		}
		
		private int? _kOD;
		public virtual int? KOD
		{
			get
			{
				return this._kOD;
			}
			set
			{
				this._kOD = value;
			}
		}
		
		private string _nAME;
		public virtual string NAME
		{
			get
			{
				return this._nAME;
			}
			set
			{
				this._nAME = value;
			}
		}
		
		private short? _iSPENIPRESENT;
		public virtual short? ISPENIPRESENT
		{
			get
			{
				return this._iSPENIPRESENT;
			}
			set
			{
				this._iSPENIPRESENT = value;
			}
		}
		
		private int? _aDELAYYEAR;
		public virtual int? ADELAYYEAR
		{
			get
			{
				return this._aDELAYYEAR;
			}
			set
			{
				this._aDELAYYEAR = value;
			}
		}
		
		private int? _aDELAYMONTH;
		public virtual int? ADELAYMONTH
		{
			get
			{
				return this._aDELAYMONTH;
			}
			set
			{
				this._aDELAYMONTH = value;
			}
		}
		
		private int? _aDELAYDAY;
		public virtual int? ADELAYDAY
		{
			get
			{
				return this._aDELAYDAY;
			}
			set
			{
				this._aDELAYDAY = value;
			}
		}
		
		private int? _pRIORITET;
		public virtual int? PRIORITET
		{
			get
			{
				return this._pRIORITET;
			}
			set
			{
				this._pRIORITET = value;
			}
		}
		
		private short? _pERCENT;
		public virtual short? PERCENT
		{
			get
			{
				return this._pERCENT;
			}
			set
			{
				this._pERCENT = value;
			}
		}
		
		private DateTime? _bEGINDATE;
		public virtual DateTime? BEGINDATE
		{
			get
			{
				return this._bEGINDATE;
			}
			set
			{
				this._bEGINDATE = value;
			}
		}
		
		private int? _cHILDBALANCE_KOD;
		public virtual int? CHILDBALANCE_KOD
		{
			get
			{
				return this._cHILDBALANCE_KOD;
			}
			set
			{
				this._cHILDBALANCE_KOD = value;
			}
		}
		
		private string _vOLUMERECOUNTFORMULA;
		public virtual string VOLUMERECOUNTFORMULA
		{
			get
			{
				return this._vOLUMERECOUNTFORMULA;
			}
			set
			{
				this._vOLUMERECOUNTFORMULA = value;
			}
		}
		
		private short? _cALCOVERDUESALDO;
		public virtual short? CALCOVERDUESALDO
		{
			get
			{
				return this._cALCOVERDUESALDO;
			}
			set
			{
				this._cALCOVERDUESALDO = value;
			}
		}
		
		private int? _eXTORGCD;
		public virtual int? EXTORGCD
		{
			get
			{
				return this._eXTORGCD;
			}
			set
			{
				this._eXTORGCD = value;
			}
		}
		
		private int? _iSCOUNTERLCHARCD;
		public virtual int? ISCOUNTERLCHARCD
		{
			get
			{
				return this._iSCOUNTERLCHARCD;
			}
			set
			{
				this._iSCOUNTERLCHARCD = value;
			}
		}
		
		private int? _cHECKABONENTACTIVEMODULEID;
		public virtual int? CHECKABONENTACTIVEMODULEID
		{
			get
			{
				return this._cHECKABONENTACTIVEMODULEID;
			}
			set
			{
				this._cHECKABONENTACTIVEMODULEID = value;
			}
		}
		
		private int? _sYSTEMBALANCE_KOD;
		public virtual int? SYSTEMBALANCE_KOD
		{
			get
			{
				return this._sYSTEMBALANCE_KOD;
			}
			set
			{
				this._sYSTEMBALANCE_KOD = value;
			}
		}
		
		private int? _cHECKACTIVELCHARCD;
		public virtual int? CHECKACTIVELCHARCD
		{
			get
			{
				return this._cHECKACTIVELCHARCD;
			}
			set
			{
				this._cHECKACTIVELCHARCD = value;
			}
		}
		
		private short? _iSAGENTSERVICE;
		public virtual short? ISAGENTSERVICE
		{
			get
			{
				return this._iSAGENTSERVICE;
			}
			set
			{
				this._iSAGENTSERVICE = value;
			}
		}
		
		private int? _vIRTALGID;
		public virtual int? VIRTALGID
		{
			get
			{
				return this._vIRTALGID;
			}
			set
			{
				this._vIRTALGID = value;
			}
		}
		
		private int? _vIRTUALBALANCEBASE;
		public virtual int? VIRTUALBALANCEBASE
		{
			get
			{
				return this._vIRTUALBALANCEBASE;
			}
			set
			{
				this._vIRTUALBALANCEBASE = value;
			}
		}
		
		private int? _fULLSUMMA_PRECISION;
		public virtual int? FULLSUMMA_PRECISION
		{
			get
			{
				return this._fULLSUMMA_PRECISION;
			}
			set
			{
				this._fULLSUMMA_PRECISION = value;
			}
		}
		
		private int? _fULLVOLUME_PRECISION;
		public virtual int? FULLVOLUME_PRECISION
		{
			get
			{
				return this._fULLVOLUME_PRECISION;
			}
			set
			{
				this._fULLVOLUME_PRECISION = value;
			}
		}
		
		private int? _lGOTSUMMA_PRECISION;
		public virtual int? LGOTSUMMA_PRECISION
		{
			get
			{
				return this._lGOTSUMMA_PRECISION;
			}
			set
			{
				this._lGOTSUMMA_PRECISION = value;
			}
		}
		
		private int? _lGOTVOLUME_PRECISION;
		public virtual int? LGOTVOLUME_PRECISION
		{
			get
			{
				return this._lGOTVOLUME_PRECISION;
			}
			set
			{
				this._lGOTVOLUME_PRECISION = value;
			}
		}
		
		private string _cOMMISSIONFROMABONENT;
		public virtual string COMMISSIONFROMABONENT
		{
			get
			{
				return this._cOMMISSIONFROMABONENT;
			}
			set
			{
				this._cOMMISSIONFROMABONENT = value;
			}
		}
		
		private short? _pAYREQUISITESFROMHOUSE;
		public virtual short? PAYREQUISITESFROMHOUSE
		{
			get
			{
				return this._pAYREQUISITESFROMHOUSE;
			}
			set
			{
				this._pAYREQUISITESFROMHOUSE = value;
			}
		}
		
		private LCHARSLIST _lCHARSLIST;
		public virtual LCHARSLIST LCHARSLIST
		{
			get
			{
				return this._lCHARSLIST;
			}
			set
			{
				this._lCHARSLIST = value;
			}
		}
		
		private LCHARSLIST _lCHARSLIST1;
		public virtual LCHARSLIST LCHARSLIST1
		{
			get
			{
				return this._lCHARSLIST1;
			}
			set
			{
				this._lCHARSLIST1 = value;
			}
		}
		
		private BALANCESLIST _bALANCESLIST1;
		public virtual BALANCESLIST BALANCESLIST1
		{
			get
			{
				return this._bALANCESLIST1;
			}
			set
			{
				this._bALANCESLIST1 = value;
			}
		}
		
		private BALANCESLIST _bALANCESLIST2;
		public virtual BALANCESLIST BALANCESLIST2
		{
			get
			{
				return this._bALANCESLIST2;
			}
			set
			{
				this._bALANCESLIST2 = value;
			}
		}
		
		private IList<LCHARSLIST> _lCHARSLISTs = new List<LCHARSLIST>();
		public virtual IList<LCHARSLIST> LCHARSLISTs
		{
			get
			{
				return this._lCHARSLISTs;
			}
		}
		
		private IList<CCHARSLIST> _cCHARSLISTs = new List<CCHARSLIST>();
		public virtual IList<CCHARSLIST> CCHARSLISTs
		{
			get
			{
				return this._cCHARSLISTs;
			}
		}
		
		private IList<BALANCESLIST> _bALANCESLISTs = new List<BALANCESLIST>();
		public virtual IList<BALANCESLIST> BALANCESLISTs
		{
			get
			{
				return this._bALANCESLISTs;
			}
		}
		
		private IList<BALANCESLIST> _bALANCESLISTs1 = new List<BALANCESLIST>();
		public virtual IList<BALANCESLIST> BALANCESLISTs1
		{
			get
			{
				return this._bALANCESLISTs1;
			}
		}
		
	}
}
#pragma warning restore 1591
