#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace aConverterClassLibrary.RecordsDataAccessORM	
{
	public partial class CHARVAL
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private int? _aDDCHARCD;
		public virtual int? ADDCHARCD
		{
			get
			{
				return this._aDDCHARCD;
			}
			set
			{
				this._aDDCHARCD = value;
			}
		}
		
		private int? _aDDCVALUE;
		public virtual int? ADDCVALUE
		{
			get
			{
				return this._aDDCVALUE;
			}
			set
			{
				this._aDDCVALUE = value;
			}
		}
		
		private string _aDDCNAME;
		public virtual string ADDCNAME
		{
			get
			{
				return this._aDDCNAME;
			}
			set
			{
				this._aDDCNAME = value;
			}
		}
		
	}
}
#pragma warning restore 1591
