#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace aConverterClassLibrary.RecordsDataAccessORM	
{
	public partial class CNV_CNTRSIND
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _cOUNTERID;
		public virtual string COUNTERID
		{
			get
			{
				return this._cOUNTERID;
			}
			set
			{
				this._cOUNTERID = value;
			}
		}
		
		private string _dOCUMENTCD;
		public virtual string DOCUMENTCD
		{
			get
			{
				return this._dOCUMENTCD;
			}
			set
			{
				this._dOCUMENTCD = value;
			}
		}
		
		private decimal? _oLDIND;
		public virtual decimal? OLDIND
		{
			get
			{
				return this._oLDIND;
			}
			set
			{
				this._oLDIND = value;
			}
		}
		
		private decimal? _oB_EM;
		public virtual decimal? OB_EM
		{
			get
			{
				return this._oB_EM;
			}
			set
			{
				this._oB_EM = value;
			}
		}
		
		private decimal? _iNDICATION;
		public virtual decimal? INDICATION
		{
			get
			{
				return this._iNDICATION;
			}
			set
			{
				this._iNDICATION = value;
			}
		}
		
		private DateTime? _iNDDATE;
		public virtual DateTime? INDDATE
		{
			get
			{
				return this._iNDDATE;
			}
			set
			{
				this._iNDDATE = value;
			}
		}
		
		private int? _iNDTYPE;
		public virtual int? INDTYPE
		{
			get
			{
				return this._iNDTYPE;
			}
			set
			{
				this._iNDTYPE = value;
			}
		}

        private int? _cASETYPE;
        public virtual int? CASETYPE
        {
            get
            {
                return this._cASETYPE;
            }
            set
            {
                this._cASETYPE = value;
            }
        }
    }
}
#pragma warning restore 1591
