#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace aConverterClassLibrary.RecordsDataAccessORM	
{
	public partial class CNV_NACHOPL
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _lSHET;
		public virtual string LSHET
		{
			get
			{
				return this._lSHET;
			}
			set
			{
				this._lSHET = value;
			}
		}
		
		private int _mONTH_;
		public virtual int MONTH_
		{
			get
			{
				return this._mONTH_;
			}
			set
			{
				this._mONTH_ = value;
			}
		}
		
		private int _yEAR_;
		public virtual int YEAR_
		{
			get
			{
				return this._yEAR_;
			}
			set
			{
				this._yEAR_ = value;
			}
		}
		
		private int _mONTH2;
		public virtual int MONTH2
		{
			get
			{
				return this._mONTH2;
			}
			set
			{
				this._mONTH2 = value;
			}
		}
		
		private int _yEAR2;
		public virtual int YEAR2
		{
			get
			{
				return this._yEAR2;
			}
			set
			{
				this._yEAR2 = value;
			}
		}
		
		private decimal _bDEBET;
		public virtual decimal BDEBET
		{
			get
			{
				return this._bDEBET;
			}
			set
			{
				this._bDEBET = value;
			}
		}
		
		private decimal _fNATH;
		public virtual decimal FNATH
		{
			get
			{
				return this._fNATH;
			}
			set
			{
				this._fNATH = value;
			}
		}
		
		private decimal _pROCHL;
		public virtual decimal PROCHL
		{
			get
			{
				return this._pROCHL;
			}
			set
			{
				this._pROCHL = value;
			}
		}
		
		private decimal _oPLATA;
		public virtual decimal OPLATA
		{
			get
			{
				return this._oPLATA;
			}
			set
			{
				this._oPLATA = value;
			}
		}
		
		private decimal _eDEBET;
		public virtual decimal EDEBET
		{
			get
			{
				return this._eDEBET;
			}
			set
			{
				this._eDEBET = value;
			}
		}
		
		private int _sERVICECD;
		public virtual int SERVICECD
		{
			get
			{
				return this._sERVICECD;
			}
			set
			{
				this._sERVICECD = value;
			}
		}
		
		private string _sERVICENAME;
		public virtual string SERVICENAME
		{
			get
			{
				return this._sERVICENAME;
			}
			set
			{
				this._sERVICENAME = value;
			}
		}
		
	}
}
#pragma warning restore 1591
