#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace aConverterClassLibrary.RecordsDataAccessORM	
{
	public partial class CNV_SUPPLNET
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _lSHET;
		public virtual string LSHET
		{
			get
			{
				return this._lSHET;
			}
			set
			{
				this._lSHET = value;
			}
		}
		
		private int? _sERVICECD;
		public virtual int? SERVICECD
		{
			get
			{
				return this._sERVICECD;
			}
			set
			{
				this._sERVICECD = value;
			}
		}
		
		private int? _kNOTL1CD;
		public virtual int? KNOTL1CD
		{
			get
			{
				return this._kNOTL1CD;
			}
			set
			{
				this._kNOTL1CD = value;
			}
		}
		
		private string _kNOTL1NAME;
		public virtual string KNOTL1NAME
		{
			get
			{
				return this._kNOTL1NAME;
			}
			set
			{
				this._kNOTL1NAME = value;
			}
		}
		
		private int? _kNOTL2CD;
		public virtual int? KNOTL2CD
		{
			get
			{
				return this._kNOTL2CD;
			}
			set
			{
				this._kNOTL2CD = value;
			}
		}
		
		private string _kNOTL2NAME;
		public virtual string KNOTL2NAME
		{
			get
			{
				return this._kNOTL2NAME;
			}
			set
			{
				this._kNOTL2NAME = value;
			}
		}
		
		private DateTime? _sUPPDATE;
		public virtual DateTime? SUPPDATE
		{
			get
			{
				return this._sUPPDATE;
			}
			set
			{
				this._sUPPDATE = value;
			}
		}
		
		private short? _cONNECTED;
		public virtual short? CONNECTED
		{
			get
			{
				return this._cONNECTED;
			}
			set
			{
				this._cONNECTED = value;
			}
		}
		
	}
}
#pragma warning restore 1591
