#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace aConverterClassLibrary.RecordsDataAccessORM	
{
	public partial class CNV_CITIZEN
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _lSHET;
		public virtual string LSHET
		{
			get
			{
				return this._lSHET;
			}
			set
			{
				this._lSHET = value;
			}
		}
		
		private int? _cITIZENID;
		public virtual int? CITIZENID
		{
			get
			{
				return this._cITIZENID;
			}
			set
			{
				this._cITIZENID = value;
			}
		}
		
		private string _f;
		public virtual string F
		{
			get
			{
				return this._f;
			}
			set
			{
				this._f = value;
			}
		}
		
		private string _i;
		public virtual string I
		{
			get
			{
				return this._i;
			}
			set
			{
				this._i = value;
			}
		}
		
		private string _o;
		public virtual string O
		{
			get
			{
				return this._o;
			}
			set
			{
				this._o = value;
			}
		}
		
		private DateTime? _bIRTHDATE;
		public virtual DateTime? BIRTHDATE
		{
			get
			{
				return this._bIRTHDATE;
			}
			set
			{
				this._bIRTHDATE = value;
			}
		}
		
		private DateTime? _sTARTDATE;
		public virtual DateTime? STARTDATE
		{
			get
			{
				return this._sTARTDATE;
			}
			set
			{
				this._sTARTDATE = value;
			}
		}
		
		private DateTime? _eNDDATE;
		public virtual DateTime? ENDDATE
		{
			get
			{
				return this._eNDDATE;
			}
			set
			{
				this._eNDDATE = value;
			}
		}
		
		private int? _lGOTA;
		public virtual int? LGOTA
		{
			get
			{
				return this._lGOTA;
			}
			set
			{
				this._lGOTA = value;
			}
		}
		
		private string _lGOTANAME;
		public virtual string LGOTANAME
		{
			get
			{
				return this._lGOTANAME;
			}
			set
			{
				this._lGOTANAME = value;
			}
		}
		
		private DateTime? _dATWP;
		public virtual DateTime? DATWP
		{
			get
			{
				return this._dATWP;
			}
			set
			{
				this._dATWP = value;
			}
		}
		
		private DateTime? _dATUP;
		public virtual DateTime? DATUP
		{
			get
			{
				return this._dATUP;
			}
			set
			{
				this._dATUP = value;
			}
		}
		
		private string _dOCUMENTNAME;
		public virtual string DOCUMENTNAME
		{
			get
			{
				return this._dOCUMENTNAME;
			}
			set
			{
				this._dOCUMENTNAME = value;
			}
		}
		
		private string _sERIA;
		public virtual string SERIA
		{
			get
			{
				return this._sERIA;
			}
			set
			{
				this._sERIA = value;
			}
		}
		
		private string _nOMER;
		public virtual string NOMER
		{
			get
			{
				return this._nOMER;
			}
			set
			{
				this._nOMER = value;
			}
		}
		
		private DateTime? _dATDN;
		public virtual DateTime? DATDN
		{
			get
			{
				return this._dATDN;
			}
			set
			{
				this._dATDN = value;
			}
		}
		
		private string _dORGNAME;
		public virtual string DORGNAME
		{
			get
			{
				return this._dORGNAME;
			}
			set
			{
				this._dORGNAME = value;
			}
		}
		
		private int? _kOLLG;
		public virtual int? KOLLG
		{
			get
			{
				return this._kOLLG;
			}
			set
			{
				this._kOLLG = value;
			}
		}
		
		private int? _hOZ;
		public virtual int? HOZ
		{
			get
			{
				return this._hOZ;
			}
			set
			{
				this._hOZ = value;
			}
		}
		
		private string _bIRTHPLACE;
		public virtual string BIRTHPLACE
		{
			get
			{
				return this._bIRTHPLACE;
			}
			set
			{
				this._bIRTHPLACE = value;
			}
		}
		
		private int? _sOB;
		public virtual int? SOB
		{
			get
			{
				return this._sOB;
			}
			set
			{
				this._sOB = value;
			}
		}
		
		private decimal? _dOLYA;
		public virtual decimal? DOLYA
		{
			get
			{
				return this._dOLYA;
			}
			set
			{
				this._dOLYA = value;
			}
		}
		
		private string _cOMMENT_;
		public virtual string COMMENT_
		{
			get
			{
				return this._cOMMENT_;
			}
			set
			{
				this._cOMMENT_ = value;
			}
		}
		
		private string _pRIBYT;
		public virtual string PRIBYT
		{
			get
			{
				return this._pRIBYT;
			}
			set
			{
				this._pRIBYT = value;
			}
		}
		
		private string _vREMREG;
		public virtual string VREMREG
		{
			get
			{
				return this._vREMREG;
			}
			set
			{
				this._vREMREG = value;
			}
		}
		
	}
}
#pragma warning restore 1591
