#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace aConverterClassLibrary.RecordsDataAccessORM	
{
	public partial class CNV_COUNTER
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _cOUNTERID;
		public virtual string COUNTERID
		{
			get
			{
				return this._cOUNTERID;
			}
			set
			{
				this._cOUNTERID = value;
			}
		}
		
		private string _lSHET;
		public virtual string LSHET
		{
			get
			{
				return this._lSHET;
			}
			set
			{
				this._lSHET = value;
			}
		}
		
		private int? _cNTTYPE;
		public virtual int? CNTTYPE
		{
			get
			{
				return this._cNTTYPE;
			}
			set
			{
				this._cNTTYPE = value;
			}
		}
		
		private string _cNTNAME;
		public virtual string CNTNAME
		{
			get
			{
				return this._cNTNAME;
			}
			set
			{
				this._cNTNAME = value;
			}
		}
		
		private DateTime? _sETUPDATE;
		public virtual DateTime? SETUPDATE
		{
			get
			{
				return this._sETUPDATE;
			}
			set
			{
				this._sETUPDATE = value;
			}
		}
		
		private string _sERIALNUM;
		public virtual string SERIALNUM
		{
			get
			{
				return this._sERIALNUM;
			}
			set
			{
				this._sERIALNUM = value;
			}
		}
		
		private int? _sETUPPLACE;
		public virtual int? SETUPPLACE
		{
			get
			{
				return this._sETUPPLACE;
			}
			set
			{
				this._sETUPPLACE = value;
			}
		}
		
		private DateTime? _pLOMBDATE;
		public virtual DateTime? PLOMBDATE
		{
			get
			{
				return this._pLOMBDATE;
			}
			set
			{
				this._pLOMBDATE = value;
			}
		}
		
		private string _pLOMBNAME;
		public virtual string PLOMBNAME
		{
			get
			{
				return this._pLOMBNAME;
			}
			set
			{
				this._pLOMBNAME = value;
			}
		}
		
		private DateTime? _lASTPOV;
		public virtual DateTime? LASTPOV
		{
			get
			{
				return this._lASTPOV;
			}
			set
			{
				this._lASTPOV = value;
			}
		}
		
		private DateTime? _nEXTPOV;
		public virtual DateTime? NEXTPOV
		{
			get
			{
				return this._nEXTPOV;
			}
			set
			{
				this._nEXTPOV = value;
			}
		}
		
		private string _pRIM_;
		public virtual string PRIM_
		{
			get
			{
				return this._pRIM_;
			}
			set
			{
				this._pRIM_ = value;
			}
		}
		
		private DateTime? _dEACTDATE;
		public virtual DateTime? DEACTDATE
		{
			get
			{
				return this._dEACTDATE;
			}
			set
			{
				this._dEACTDATE = value;
			}
		}
		
		private string _tAG;
		public virtual string TAG
		{
			get
			{
				return this._tAG;
			}
			set
			{
				this._tAG = value;
			}
		}

        private string _gUID_;
        public virtual string GUID_
        {
            get
            {
                return this._gUID_;
            }
            set
            {
                this._gUID_ = value;
            }
        }

        private string _nAME;
		public virtual string NAME
		{
			get
			{
				return this._nAME;
			}
			set
			{
				this._nAME = value;
			}
		}

        private int? _sTATUSID;
        public virtual int? STATUSID
        {
            get
            {
                return this._sTATUSID;
            }
            set
            {
                this._sTATUSID = value;
            }
        }

        private DateTime? _sTATUSDATE;
        public virtual DateTime? STATUSDATE
        {
            get
            {
                return this._sTATUSDATE;
            }
            set
            {
                this._sTATUSDATE = value;
            }
        }

        private int _cOUNTER_LEVEL;
        public virtual int COUNTER_LEVEL
        {
            get
            {
                return this._cOUNTER_LEVEL;
            }
            set
            {
                this._cOUNTER_LEVEL = value;
            }
        }

        private int? _tARGETBALANCE_KOD;
        public virtual int? TARGETBALANCE_KOD
        {
            get
            {
                return this._tARGETBALANCE_KOD;
            }
            set
            {
                this._tARGETBALANCE_KOD = value;
            }
        }

        private int? _dISTRIBUTINGMETHOD;
        public virtual int? DISTRIBUTINGMETHOD
        {
            get
            {
                return this._dISTRIBUTINGMETHOD;
            }
            set
            {
                this._dISTRIBUTINGMETHOD = value;
            }
        }

        private int? _tARGETNEGATIVEBALANCE_KOD;
        public virtual int? TARGETNEGATIVEBALANCE_KOD
        {
            get
            {
                return this._tARGETNEGATIVEBALANCE_KOD;
            }
            set
            {
                this._tARGETNEGATIVEBALANCE_KOD = value;
            }
        }

        private int? _gROUPCOUNTERMODULEID;
        public virtual int? GROUPCOUNTERMODULEID
        {
            get
            {
                return this._gROUPCOUNTERMODULEID;
            }
            set
            {
                this._gROUPCOUNTERMODULEID = value;
            }
        }

        private int? _kODREGIM;
        public virtual int? KODREGIM
        {
            get
            {
                return this._kODREGIM;
            }
            set
            {
                this._kODREGIM = value;
            }
        }

        private int? _nOCALCCHILDBALANCES;
        public virtual int? NOCALCCHILDBALANCES
        {
            get
            {
                return this._nOCALCCHILDBALANCES;
            }
            set
            {
                this._nOCALCCHILDBALANCES = value;
            }
        }

        private string _uNTINGID;
        public virtual string UNTINGID
        {
            get
            {
                return this._uNTINGID;
            }
            set
            {
                this._uNTINGID = value;
            }
        }
    }
}
#pragma warning restore 1591
