#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace aConverterClassLibrary.RecordsDataAccessORM	
{
	public partial class CNV_EQUIPMENT
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _lSHET;
		public virtual string LSHET
		{
			get
			{
				return this._lSHET;
			}
			set
			{
				this._lSHET = value;
			}
		}
		
		private int? _gROUPKOD;
		public virtual int? GROUPKOD
		{
			get
			{
				return this._gROUPKOD;
			}
			set
			{
				this._gROUPKOD = value;
			}
		}
		
		private string _gROUPNAME;
		public virtual string GROUPNAME
		{
			get
			{
				return this._gROUPNAME;
			}
			set
			{
				this._gROUPNAME = value;
			}
		}
		
		private int? _mARKKOD;
		public virtual int? MARKKOD
		{
			get
			{
				return this._mARKKOD;
			}
			set
			{
				this._mARKKOD = value;
			}
		}
		
		private string _mARKNAME;
		public virtual string MARKNAME
		{
			get
			{
				return this._mARKNAME;
			}
			set
			{
				this._mARKNAME = value;
			}
		}
		
		private DateTime? _sETUPDATE;
		public virtual DateTime? SETUPDATE
		{
			get
			{
				return this._sETUPDATE;
			}
			set
			{
				this._sETUPDATE = value;
			}
		}
		
		private string _sERIALNUM;
		public virtual string SERIALNUM
		{
			get
			{
				return this._sERIALNUM;
			}
			set
			{
				this._sERIALNUM = value;
			}
		}
		
	}
}
#pragma warning restore 1591
