#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace aConverterClassLibrary.RecordsDataAccessORM	
{
	public partial class CNV_PENI
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _lSHET;
		public virtual string LSHET
		{
			get
			{
				return this._lSHET;
			}
			set
			{
				this._lSHET = value;
			}
		}
		
		private int _sERVICECD;
		public virtual int SERVICECD
		{
			get
			{
				return this._sERVICECD;
			}
			set
			{
				this._sERVICECD = value;
			}
		}
		
		private DateTime _dOLGDATE;
		public virtual DateTime DOLGDATE
		{
			get
			{
				return this._dOLGDATE;
			}
			set
			{
				this._dOLGDATE = value;
			}
		}
		
		private decimal _dOLG;
		public virtual decimal DOLG
		{
			get
			{
				return this._dOLG;
			}
			set
			{
				this._dOLG = value;
			}
		}
		
	}
}
#pragma warning restore 1591
