#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace aConverterClassLibrary.RecordsDataAccessORM	
{
	public partial class CNV_CITIZENMIGRATION
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private int _cITIZENID;
		public virtual int CITIZENID
		{
			get
			{
				return this._cITIZENID;
			}
			set
			{
				this._cITIZENID = value;
			}
		}
		
		private DateTime _dATE_;
		public virtual DateTime DATE_
		{
			get
			{
				return this._dATE_;
			}
			set
			{
				this._dATE_ = value;
			}
		}
		
		private int _mIGRATIONTYPE;
		public virtual int MIGRATIONTYPE
		{
			get
			{
				return this._mIGRATIONTYPE;
			}
			set
			{
				this._mIGRATIONTYPE = value;
			}
		}
		
		private int _dIRECTION;
		public virtual int DIRECTION
		{
			get
			{
				return this._dIRECTION;
			}
			set
			{
				this._dIRECTION = value;
			}
		}
		
	}
}
#pragma warning restore 1591
