#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace aConverterClassLibrary.RecordsDataAccessORM	
{
	public partial class CNV_OPLATA
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _lSHET;
		public virtual string LSHET
		{
			get
			{
				return this._lSHET;
			}
			set
			{
				this._lSHET = value;
			}
		}
		
		private string _dOCUMENTCD;
		public virtual string DOCUMENTCD
		{
			get
			{
				return this._dOCUMENTCD;
			}
			set
			{
				this._dOCUMENTCD = value;
			}
		}
		
		private int _mONTH_;
		public virtual int MONTH_
		{
			get
			{
				return this._mONTH_;
			}
			set
			{
				this._mONTH_ = value;
			}
		}
		
		private int _yEAR_;
		public virtual int YEAR_
		{
			get
			{
				return this._yEAR_;
			}
			set
			{
				this._yEAR_ = value;
			}
		}
		
		private decimal _sUMMA;
		public virtual decimal SUMMA
		{
			get
			{
				return this._sUMMA;
			}
			set
			{
				this._sUMMA = value;
			}
		}
		
		private DateTime _dATE_;
		public virtual DateTime DATE_
		{
			get
			{
				return this._dATE_;
			}
			set
			{
				this._dATE_ = value;
			}
		}
		
		private DateTime _dATE_VV;
		public virtual DateTime DATE_VV
		{
			get
			{
				return this._dATE_VV;
			}
			set
			{
				this._dATE_VV = value;
			}
		}
		
		private DateTime? _dATETIND;
		public virtual DateTime? DATETIND
		{
			get
			{
				return this._dATETIND;
			}
			set
			{
				this._dATETIND = value;
			}
		}
		
		private int _sOURCECD;
		public virtual int SOURCECD
		{
			get
			{
				return this._sOURCECD;
			}
			set
			{
				this._sOURCECD = value;
			}
		}
		
		private string _sOURCENAME;
		public virtual string SOURCENAME
		{
			get
			{
				return this._sOURCENAME;
			}
			set
			{
				this._sOURCENAME = value;
			}
		}
		
		private int _sERVICECD;
		public virtual int SERVICECD
		{
			get
			{
				return this._sERVICECD;
			}
			set
			{
				this._sERVICECD = value;
			}
		}
		
		private string _pRIM_;
		public virtual string PRIM_
		{
			get
			{
				return this._pRIM_;
			}
			set
			{
				this._pRIM_ = value;
			}
		}
		
		private string _sERVICENAME;
		public virtual string SERVICENAME
		{
			get
			{
				return this._sERVICENAME;
			}
			set
			{
				this._sERVICENAME = value;
			}
		}
		
	}
}
#pragma warning restore 1591
