#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace aConverterClassLibrary.RecordsDataAccessORM	
{
	public partial class CNV_ABONENT
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _lSHET;
		public virtual string LSHET
		{
			get
			{
				return this._lSHET;
			}
			set
			{
				this._lSHET = value;
			}
		}
		
		private int? _hOUSECD;
		public virtual int? HOUSECD
		{
			get
			{
				return this._hOUSECD;
			}
			set
			{
				this._hOUSECD = value;
			}
		}
		
		private int? _dISTKOD;
		public virtual int? DISTKOD
		{
			get
			{
				return this._dISTKOD;
			}
			set
			{
				this._dISTKOD = value;
			}
		}
		
		private string _dISTNAME;
		public virtual string DISTNAME
		{
			get
			{
				return this._dISTNAME;
			}
			set
			{
				this._dISTNAME = value;
			}
		}
		
		private int? _rAYONKOD;
		public virtual int? RAYONKOD
		{
			get
			{
				return this._rAYONKOD;
			}
			set
			{
				this._rAYONKOD = value;
			}
		}
		
		private string _rAYONNAME;
		public virtual string RAYONNAME
		{
			get
			{
				return this._rAYONNAME;
			}
			set
			{
				this._rAYONNAME = value;
			}
		}

        private int? _sETTLEMENTKOD;
        public virtual int? SETTLEMENTKOD
        {
            get
            {
                return this._sETTLEMENTKOD;
            }
            set
            {
                this._sETTLEMENTKOD = value;
            }
        }

        private string _sETTLEMENTNAME;
        public virtual string SETTLEMENTNAME
        {
            get
            {
                return this._sETTLEMENTNAME;
            }
            set
            {
                this._sETTLEMENTNAME = value;
            }
        }

        private int? _tOWNSKOD;
		public virtual int? TOWNSKOD
		{
			get
			{
				return this._tOWNSKOD;
			}
			set
			{
				this._tOWNSKOD = value;
			}
		}
		
		private string _tOWNSNAME;
		public virtual string TOWNSNAME
		{
			get
			{
				return this._tOWNSNAME;
			}
			set
			{
				this._tOWNSNAME = value;
			}
		}
		
		private int? _uLICAKOD;
		public virtual int? ULICAKOD
		{
			get
			{
				return this._uLICAKOD;
			}
			set
			{
				this._uLICAKOD = value;
			}
		}
		
		private string _uLICANAME;
		public virtual string ULICANAME
		{
			get
			{
				return this._uLICANAME;
			}
			set
			{
				this._uLICANAME = value;
			}
		}
		
		private string _f;
		public virtual string F
		{
			get
			{
				return this._f;
			}
			set
			{
				this._f = value;
			}
		}
		
		private string _i;
		public virtual string I
		{
			get
			{
				return this._i;
			}
			set
			{
				this._i = value;
			}
		}
		
		private string _o;
		public virtual string O
		{
			get
			{
				return this._o;
			}
			set
			{
				this._o = value;
			}
		}
		
		private string _pRIM_;
		public virtual string PRIM_
		{
			get
			{
				return this._pRIM_;
			}
			set
			{
				this._pRIM_ = value;
			}
		}
		
		private string _eXTLSHET;
		public virtual string EXTLSHET
		{
			get
			{
				return this._eXTLSHET;
			}
			set
			{
				this._eXTLSHET = value;
			}
		}
		
		private string _eXTLSHET2;
		public virtual string EXTLSHET2
		{
			get
			{
				return this._eXTLSHET2;
			}
			set
			{
				this._eXTLSHET2 = value;
			}
		}
		
		private string _pHONENUM;
		public virtual string PHONENUM
		{
			get
			{
				return this._pHONENUM;
			}
			set
			{
				this._pHONENUM = value;
			}
		}
		
		private string _pOSTINDEX;
		public virtual string POSTINDEX
		{
			get
			{
				return this._pOSTINDEX;
			}
			set
			{
				this._pOSTINDEX = value;
			}
		}
		
		private int? _dUCD;
		public virtual int? DUCD
		{
			get
			{
				return this._dUCD;
			}
			set
			{
				this._dUCD = value;
			}
		}
		
		private string _dUNAME;
		public virtual string DUNAME
		{
			get
			{
				return this._dUNAME;
			}
			set
			{
				this._dUNAME = value;
			}
		}
		
		private int? _iSDELETED;
		public virtual int? ISDELETED
		{
			get
			{
				return this._iSDELETED;
			}
			set
			{
				this._iSDELETED = value;
			}
		}
		
		private string _kORPUSPOSTFIX;
		public virtual string KORPUSPOSTFIX
		{
			get
			{
				return this._kORPUSPOSTFIX;
			}
			set
			{
				this._kORPUSPOSTFIX = value;
			}
		}
		
		private int? _kORPUSNO;
		public virtual int? KORPUSNO
		{
			get
			{
				return this._kORPUSNO;
			}
			set
			{
				this._kORPUSNO = value;
			}
		}
		
		private string _hOUSEPOSTFIX;
		public virtual string HOUSEPOSTFIX
		{
			get
			{
				return this._hOUSEPOSTFIX;
			}
			set
			{
				this._hOUSEPOSTFIX = value;
			}
		}
		
		private string _hOUSENO;
		public virtual string HOUSENO
		{
			get
			{
				return this._hOUSENO;
			}
			set
			{
				this._hOUSENO = value;
			}
		}
		
		private string _fLATPOSTFIX;
		public virtual string FLATPOSTFIX
		{
			get
			{
				return this._fLATPOSTFIX;
			}
			set
			{
				this._fLATPOSTFIX = value;
			}
		}
		
		private short _rOOMNO;
		public virtual short ROOMNO
		{
			get
			{
				return this._rOOMNO;
			}
			set
			{
				this._rOOMNO = value;
			}
		}
		
		private int? _fLATNO;
		public virtual int? FLATNO
		{
			get
			{
				return this._fLATNO;
			}
			set
			{
				this._fLATNO = value;
			}
		}
		
		private string _rOOMPOSTFIX;
		public virtual string ROOMPOSTFIX
		{
			get
			{
				return this._rOOMPOSTFIX;
			}
			set
			{
				this._rOOMPOSTFIX = value;
			}
		}
		
		private DateTime? _cLOSEDATE;
		public virtual DateTime? CLOSEDATE
		{
			get
			{
				return this._cLOSEDATE;
			}
			set
			{
				this._cLOSEDATE = value;
			}
		}
		
		private string _hOUSENOTE;
		public virtual string HOUSENOTE
		{
			get
			{
				return this._hOUSENOTE;
			}
			set
			{
				this._hOUSENOTE = value;
			}
		}

        private string _eMAIL;
        public virtual string EMAIL
        {
            get
            {
                return this._eMAIL;
            }
            set
            {
                this._eMAIL = value;
            }
        }
    }
}
#pragma warning restore 1591
