#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace aConverterClassLibrary.RecordsDataAccessORM	
{
	public partial class CNV_COUNTER
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _cOUNTERID;
		public virtual string COUNTERID
		{
			get
			{
				return this._cOUNTERID;
			}
			set
			{
				this._cOUNTERID = value;
			}
		}
		
		private string _lSHET;
		public virtual string LSHET
		{
			get
			{
				return this._lSHET;
			}
			set
			{
				this._lSHET = value;
			}
		}
		
		private int? _cNTTYPE;
		public virtual int? CNTTYPE
		{
			get
			{
				return this._cNTTYPE;
			}
			set
			{
				this._cNTTYPE = value;
			}
		}
		
		private string _cNTNAME;
		public virtual string CNTNAME
		{
			get
			{
				return this._cNTNAME;
			}
			set
			{
				this._cNTNAME = value;
			}
		}
		
		private DateTime? _sETUPDATE;
		public virtual DateTime? SETUPDATE
		{
			get
			{
				return this._sETUPDATE;
			}
			set
			{
				this._sETUPDATE = value;
			}
		}
		
		private string _sERIALNUM;
		public virtual string SERIALNUM
		{
			get
			{
				return this._sERIALNUM;
			}
			set
			{
				this._sERIALNUM = value;
			}
		}
		
		private int? _sETUPPLACE;
		public virtual int? SETUPPLACE
		{
			get
			{
				return this._sETUPPLACE;
			}
			set
			{
				this._sETUPPLACE = value;
			}
		}
		
		private string _pLACE;
		public virtual string PLACE
		{
			get
			{
				return this._pLACE;
			}
			set
			{
				this._pLACE = value;
			}
		}
		
		private DateTime? _pLOMBDATE;
		public virtual DateTime? PLOMBDATE
		{
			get
			{
				return this._pLOMBDATE;
			}
			set
			{
				this._pLOMBDATE = value;
			}
		}
		
		private string _pLOMBNAME;
		public virtual string PLOMBNAME
		{
			get
			{
				return this._pLOMBNAME;
			}
			set
			{
				this._pLOMBNAME = value;
			}
		}
		
		private DateTime? _lASTPOV;
		public virtual DateTime? LASTPOV
		{
			get
			{
				return this._lASTPOV;
			}
			set
			{
				this._lASTPOV = value;
			}
		}
		
		private DateTime? _nEXTPOV;
		public virtual DateTime? NEXTPOV
		{
			get
			{
				return this._nEXTPOV;
			}
			set
			{
				this._nEXTPOV = value;
			}
		}
		
		private string _pRIM_;
		public virtual string PRIM_
		{
			get
			{
				return this._pRIM_;
			}
			set
			{
				this._pRIM_ = value;
			}
		}
		
		private DateTime? _dEACTDATE;
		public virtual DateTime? DEACTDATE
		{
			get
			{
				return this._dEACTDATE;
			}
			set
			{
				this._dEACTDATE = value;
			}
		}
		
		private string _tAG;
		public virtual string TAG
		{
			get
			{
				return this._tAG;
			}
			set
			{
				this._tAG = value;
			}
		}
		
		private string _nAME;
		public virtual string NAME
		{
			get
			{
				return this._nAME;
			}
			set
			{
				this._nAME = value;
			}
		}
		
	}
}
#pragma warning restore 1591
