#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace aConverterClassLibrary.RecordsDataAccessORM	
{
	public partial class CNV_CHARSHOUSES
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private int _cHARCD;
		public virtual int CHARCD
		{
			get
			{
				return this._cHARCD;
			}
			set
			{
				this._cHARCD = value;
			}
		}
		
		private string _cHARNAME;
		public virtual string CHARNAME
		{
			get
			{
				return this._cHARNAME;
			}
			set
			{
				this._cHARNAME = value;
			}
		}
		
		private DateTime _dATE_;
		public virtual DateTime DATE_
		{
			get
			{
				return this._dATE_;
			}
			set
			{
				this._dATE_ = value;
			}
		}
		
		private int _hOUSECD;
		public virtual int HOUSECD
		{
			get
			{
				return this._hOUSECD;
			}
			set
			{
				this._hOUSECD = value;
			}
		}
		
		private decimal _vALUE_;
		public virtual decimal VALUE_
		{
			get
			{
				return this._vALUE_;
			}
			set
			{
				this._vALUE_ = value;
			}
		}
		
	}
}
#pragma warning restore 1591
