#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace aConverterClassLibrary.RecordsDataAccessORM	
{
	public partial class CNV_CITYZENLGOTA
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private int _cITYZENID;
		public virtual int CITYZENID
		{
			get
			{
				return this._cITYZENID;
			}
			set
			{
				this._cITYZENID = value;
			}
		}
		
		private int _lGOTACD;
		public virtual int LGOTACD
		{
			get
			{
				return this._lGOTACD;
			}
			set
			{
				this._lGOTACD = value;
			}
		}
		
		private string _lGOTANAME;
		public virtual string LGOTANAME
		{
			get
			{
				return this._lGOTANAME;
			}
			set
			{
				this._lGOTANAME = value;
			}
		}
		
		private DateTime _sTARTDATE;
		public virtual DateTime STARTDATE
		{
			get
			{
				return this._sTARTDATE;
			}
			set
			{
				this._sTARTDATE = value;
			}
		}
		
		private DateTime? _eNDDATE;
		public virtual DateTime? ENDDATE
		{
			get
			{
				return this._eNDDATE;
			}
			set
			{
				this._eNDDATE = value;
			}
		}
		
		private int _pRIORITY;
		public virtual int PRIORITY
		{
			get
			{
				return this._pRIORITY;
			}
			set
			{
				this._pRIORITY = value;
			}
		}
		
		private int _iSDELETED;
		public virtual int ISDELETED
		{
			get
			{
				return this._iSDELETED;
			}
			set
			{
				this._iSDELETED = value;
			}
		}
		
	}
}
#pragma warning restore 1591
