#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using aConverterClassLibrary.RecordsDataAccessORM;

namespace aConverterClassLibrary.RecordsDataAccessORM	
{
	public partial class AbonentConvertationEntitiesModel : OpenAccessContext, IAbonentConvertationEntitiesModelUnitOfWork
	{
		private static string connectionStringName = @"FirebirdConnectionString";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");
		
		public AbonentConvertationEntitiesModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public AbonentConvertationEntitiesModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public AbonentConvertationEntitiesModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public AbonentConvertationEntitiesModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public AbonentConvertationEntitiesModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<CNV_SUPPLNET> CNV_SUPPLNETs 
		{
			get
			{
				return this.GetAll<CNV_SUPPLNET>();
			}
		}
		
		public IQueryable<CNV_PENI> CNV_PENIs 
		{
			get
			{
				return this.GetAll<CNV_PENI>();
			}
		}

        public IQueryable<CNV_PENISUMMA> CNV_PENISUMMAs
        {
            get
            {
                return this.GetAll<CNV_PENISUMMA>();
            }
        }

        public IQueryable<CNV_OPLATA> CNV_OPLATAs 
		{
			get
			{
				return this.GetAll<CNV_OPLATA>();
			}
		}
		
		public IQueryable<CNV_NACHOPL> CNV_NACHOPLs 
		{
			get
			{
				return this.GetAll<CNV_NACHOPL>();
			}
		}
		
		public IQueryable<CNV_NACH> CNV_NACHes 
		{
			get
			{
				return this.GetAll<CNV_NACH>();
			}
		}
		
		public IQueryable<CNV_LCHAR> CNV_LCHARs 
		{
			get
			{
				return this.GetAll<CNV_LCHAR>();
			}
		}
		
		public IQueryable<CNV_HADDCHAR> CNV_HADDCHARs 
		{
			get
			{
				return this.GetAll<CNV_HADDCHAR>();
			}
		}
		
		public IQueryable<CNV_GCOUNTER> CNV_GCOUNTERs 
		{
			get
			{
				return this.GetAll<CNV_GCOUNTER>();
			}
		}
		
		public IQueryable<CNV_EQUIPMENT> CNV_EQUIPMENTs 
		{
			get
			{
				return this.GetAll<CNV_EQUIPMENT>();
			}
		}
		
		public IQueryable<CNV_DOGOVOR> CNV_DOGOVORs 
		{
			get
			{
				return this.GetAll<CNV_DOGOVOR>();
			}
		}
		
		public IQueryable<CNV_COUNTER> CNV_COUNTERs 
		{
			get
			{
				return this.GetAll<CNV_COUNTER>();
			}
		}
		
		public IQueryable<CNV_CNTRSIND> CNV_CNTRSINDs 
		{
			get
			{
				return this.GetAll<CNV_CNTRSIND>();
			}
		}
		
		public IQueryable<CNV_CITIZEN> CNV_CITIZENs 
		{
			get
			{
				return this.GetAll<CNV_CITIZEN>();
			}
		}

        public IQueryable<CNV_CITIZENRELATIONS> CNV_CITIZENRELATIONSs
        {
            get
            {
                return this.GetAll<CNV_CITIZENRELATIONS>();
            }
        }

        public IQueryable<CNV_CHARVAL> CNV_CHARVALs 
		{
			get
			{
				return this.GetAll<CNV_CHARVAL>();
			}
		}
		
		public IQueryable<CNV_CHAR> CNV_CHARs 
		{
			get
			{
				return this.GetAll<CNV_CHAR>();
			}
		}
		
		public IQueryable<CNV_ABONENT> CNV_ABONENTs 
		{
			get
			{
				return this.GetAll<CNV_ABONENT>();
			}
		}
		
		public IQueryable<EXTORGSTREET> EXTORGSTREETs 
		{
			get
			{
				return this.GetAll<EXTORGSTREET>();
			}
		}
		
		public IQueryable<LCHARSLIST> LCHARSLISTs 
		{
			get
			{
				return this.GetAll<LCHARSLIST>();
			}
		}
		
		public IQueryable<HOUSE> HOUSEs 
		{
			get
			{
				return this.GetAll<HOUSE>();
			}
		}
		
		public IQueryable<CCHARSLIST> CCHARSLISTs 
		{
			get
			{
				return this.GetAll<CCHARSLIST>();
			}
		}
		
		public IQueryable<BALANCESLIST> BALANCESLISTs 
		{
			get
			{
				return this.GetAll<BALANCESLIST>();
			}
		}
		
		public IQueryable<ABONENT> ABONENTs 
		{
			get
			{
				return this.GetAll<ABONENT>();
			}
		}
		
		public IQueryable<STREET> STREETs 
		{
			get
			{
				return this.GetAll<STREET>();
			}
		}
		
		public IQueryable<CNV_AADDCHAR> CNV_AADDCHARs 
		{
			get
			{
				return this.GetAll<CNV_AADDCHAR>();
			}
		}
		
		public IQueryable<EXTORGACCOUNT> EXTORGACCOUNTs 
		{
			get
			{
				return this.GetAll<EXTORGACCOUNT>();
			}
		}
		
		public IQueryable<CNV_CITIZENMIGRATION> CNV_CITIZENMIGRATIONs 
		{
			get
			{
				return this.GetAll<CNV_CITIZENMIGRATION>();
			}
		}
		
		public IQueryable<CNV_CHARSHOUSES> CNV_CHARSHOUSEs 
		{
			get
			{
				return this.GetAll<CNV_CHARSHOUSES>();
			}
		}
		
		public IQueryable<CNV_CITYZENLGOTA> CNV_CITYZENLGOTAs 
		{
			get
			{
				return this.GetAll<CNV_CITYZENLGOTA>();
			}
		}
		
		public IQueryable<CNV_LGOTSUMMA> CNV_LGOTSUMMAs 
		{
			get
			{
				return this.GetAll<CNV_LGOTSUMMA>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "Firebird";
			backend.ProviderName = "FirebirdSql.Data.FirebirdClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of AbonentConvertationEntitiesModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of AbonentConvertationEntitiesModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IAbonentConvertationEntitiesModelUnitOfWork : IUnitOfWork
	{
		IQueryable<CNV_SUPPLNET> CNV_SUPPLNETs
		{
			get;
		}
		IQueryable<CNV_PENI> CNV_PENIs
		{
			get;
		}
        IQueryable<CNV_PENISUMMA> CNV_PENISUMMAs
        {
            get;
        }
        IQueryable<CNV_OPLATA> CNV_OPLATAs
		{
			get;
		}
		IQueryable<CNV_NACHOPL> CNV_NACHOPLs
		{
			get;
		}
		IQueryable<CNV_NACH> CNV_NACHes
		{
			get;
		}
		IQueryable<CNV_LCHAR> CNV_LCHARs
		{
			get;
		}
		IQueryable<CNV_HADDCHAR> CNV_HADDCHARs
		{
			get;
		}
		IQueryable<CNV_GCOUNTER> CNV_GCOUNTERs
		{
			get;
		}
		IQueryable<CNV_EQUIPMENT> CNV_EQUIPMENTs
		{
			get;
		}
		IQueryable<CNV_DOGOVOR> CNV_DOGOVORs
		{
			get;
		}
		IQueryable<CNV_COUNTER> CNV_COUNTERs
		{
			get;
		}
		IQueryable<CNV_CNTRSIND> CNV_CNTRSINDs
		{
			get;
		}
		IQueryable<CNV_CITIZEN> CNV_CITIZENs
		{
			get;
		}
        IQueryable<CNV_CITIZENRELATIONS> CNV_CITIZENRELATIONSs
        {
            get;
        }
        IQueryable<CNV_CHARVAL> CNV_CHARVALs
		{
			get;
		}
		IQueryable<CNV_CHAR> CNV_CHARs
		{
			get;
		}
		IQueryable<CNV_ABONENT> CNV_ABONENTs
		{
			get;
		}
		IQueryable<EXTORGSTREET> EXTORGSTREETs
		{
			get;
		}
		IQueryable<LCHARSLIST> LCHARSLISTs
		{
			get;
		}
		IQueryable<HOUSE> HOUSEs
		{
			get;
		}
		IQueryable<CCHARSLIST> CCHARSLISTs
		{
			get;
		}
		IQueryable<BALANCESLIST> BALANCESLISTs
		{
			get;
		}
		IQueryable<ABONENT> ABONENTs
		{
			get;
		}
		IQueryable<STREET> STREETs
		{
			get;
		}
		IQueryable<CNV_AADDCHAR> CNV_AADDCHARs
		{
			get;
		}
		IQueryable<EXTORGACCOUNT> EXTORGACCOUNTs
		{
			get;
		}
		IQueryable<CNV_CITIZENMIGRATION> CNV_CITIZENMIGRATIONs
		{
			get;
		}
		IQueryable<CNV_CHARSHOUSES> CNV_CHARSHOUSEs
		{
			get;
		}
		IQueryable<CNV_CITYZENLGOTA> CNV_CITYZENLGOTAs
		{
			get;
		}
		IQueryable<CNV_LGOTSUMMA> CNV_LGOTSUMMAs
		{
			get;
		}
	}
}
#pragma warning restore 1591
