#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace aConverterClassLibrary.RecordsDataAccessORM	
{
	public partial class EXTORGSTREET
	{
		private int _eXTORGCD;
		public virtual int EXTORGCD
		{
			get
			{
				return this._eXTORGCD;
			}
			set
			{
				this._eXTORGCD = value;
			}
		}
		
		private int _sTREETCD;
		public virtual int STREETCD
		{
			get
			{
				return this._sTREETCD;
			}
			set
			{
				this._sTREETCD = value;
			}
		}
		
		private int _pUNKTCD;
		public virtual int PUNKTCD
		{
			get
			{
				return this._pUNKTCD;
			}
			set
			{
				this._pUNKTCD = value;
			}
		}
		
		private string _eXTORGSTREETCD;
		public virtual string EXTORGSTREETCD
		{
			get
			{
				return this._eXTORGSTREETCD;
			}
			set
			{
				this._eXTORGSTREETCD = value;
			}
		}
		
	}
}
#pragma warning restore 1591
