#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using aConverterClassLibrary.RecordsDataAccessORM;

namespace aConverterClassLibrary.RecordsDataAccessORM	
{
	public partial class HOUSE
	{
		private int _hOUSECD;
		public virtual int HOUSECD
		{
			get
			{
				return this._hOUSECD;
			}
			set
			{
				this._hOUSECD = value;
			}
		}
		
		private int? _mASTERID;
		public virtual int? MASTERID
		{
			get
			{
				return this._mASTERID;
			}
			set
			{
				this._mASTERID = value;
			}
		}
		
		private int? _dISTCD;
		public virtual int? DISTCD
		{
			get
			{
				return this._dISTCD;
			}
			set
			{
				this._dISTCD = value;
			}
		}
		
		private int? _dU_CD;
		public virtual int? DU_CD
		{
			get
			{
				return this._dU_CD;
			}
			set
			{
				this._dU_CD = value;
			}
		}
		
		private int? _sTREETCD;
		public virtual int? STREETCD
		{
			get
			{
				return this._sTREETCD;
			}
			set
			{
				this._sTREETCD = value;
			}
		}
		
		private int? _pUNKTCD;
		public virtual int? PUNKTCD
		{
			get
			{
				return this._pUNKTCD;
			}
			set
			{
				this._pUNKTCD = value;
			}
		}
		
		private int? _k_REMOTECD;
		public virtual int? K_REMOTECD
		{
			get
			{
				return this._k_REMOTECD;
			}
			set
			{
				this._k_REMOTECD = value;
			}
		}
		
		private int? _cAPACITYCD;
		public virtual int? CAPACITYCD
		{
			get
			{
				return this._cAPACITYCD;
			}
			set
			{
				this._cAPACITYCD = value;
			}
		}
		
		private string _hOUSENO;
		public virtual string HOUSENO
		{
			get
			{
				return this._hOUSENO;
			}
			set
			{
				this._hOUSENO = value;
			}
		}
		
		private short? _iSHOTWATER;
		public virtual short? ISHOTWATER
		{
			get
			{
				return this._iSHOTWATER;
			}
			set
			{
				this._iSHOTWATER = value;
			}
		}
		
		private int? _kADASTRCD;
		public virtual int? KADASTRCD
		{
			get
			{
				return this._kADASTRCD;
			}
			set
			{
				this._kADASTRCD = value;
			}
		}
		
		private int? _nUMBEROFKVART;
		public virtual int? NUMBEROFKVART
		{
			get
			{
				return this._nUMBEROFKVART;
			}
			set
			{
				this._nUMBEROFKVART = value;
			}
		}
		
		private string _pOSTINDEX;
		public virtual string POSTINDEX
		{
			get
			{
				return this._pOSTINDEX;
			}
			set
			{
				this._pOSTINDEX = value;
			}
		}
		
		private string _hOUSEPOSTFIX;
		public virtual string HOUSEPOSTFIX
		{
			get
			{
				return this._hOUSEPOSTFIX;
			}
			set
			{
				this._hOUSEPOSTFIX = value;
			}
		}
		
		private int? _kORPUSNO;
		public virtual int? KORPUSNO
		{
			get
			{
				return this._kORPUSNO;
			}
			set
			{
				this._kORPUSNO = value;
			}
		}
		
		private string _kORPUSPOSTFIX;
		public virtual string KORPUSPOSTFIX
		{
			get
			{
				return this._kORPUSPOSTFIX;
			}
			set
			{
				this._kORPUSPOSTFIX = value;
			}
		}
		
		private int? _eNTRANCCOUNT;
		public virtual int? ENTRANCCOUNT
		{
			get
			{
				return this._eNTRANCCOUNT;
			}
			set
			{
				this._eNTRANCCOUNT = value;
			}
		}
		
		private int? _fLOORCOUNT;
		public virtual int? FLOORCOUNT
		{
			get
			{
				return this._fLOORCOUNT;
			}
			set
			{
				this._fLOORCOUNT = value;
			}
		}
		
		private short? _bUILDINGYEAR;
		public virtual short? BUILDINGYEAR
		{
			get
			{
				return this._bUILDINGYEAR;
			}
			set
			{
				this._bUILDINGYEAR = value;
			}
		}
		
		private string _nOTE;
		public virtual string NOTE
		{
			get
			{
				return this._nOTE;
			}
			set
			{
				this._nOTE = value;
			}
		}
		
		private int? _rOUTEID;
		public virtual int? ROUTEID
		{
			get
			{
				return this._rOUTEID;
			}
			set
			{
				this._rOUTEID = value;
			}
		}
		
		private string _kLADR;
		public virtual string KLADR
		{
			get
			{
				return this._kLADR;
			}
			set
			{
				this._kLADR = value;
			}
		}
		
		private string _oKATO;
		public virtual string OKATO
		{
			get
			{
				return this._oKATO;
			}
			set
			{
				this._oKATO = value;
			}
		}
		
		private string _sOCR;
		public virtual string SOCR
		{
			get
			{
				return this._sOCR;
			}
			set
			{
				this._sOCR = value;
			}
		}
		
		private short? _iSMANYKVART;
		public virtual short? ISMANYKVART
		{
			get
			{
				return this._iSMANYKVART;
			}
			set
			{
				this._iSMANYKVART = value;
			}
		}
		
		private IList<ABONENT> _aBONENTs = new List<ABONENT>();
		public virtual IList<ABONENT> ABONENTs
		{
			get
			{
				return this._aBONENTs;
			}
		}
		
	}
}
#pragma warning restore 1591
