#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace aConverterClassLibrary.RecordsDataAccessORM	
{
	public partial class LCHAR
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _lSHET;
		public virtual string LSHET
		{
			get
			{
				return this._lSHET;
			}
			set
			{
				this._lSHET = value;
			}
		}
		
		private int? _lCHARCD;
		public virtual int? LCHARCD
		{
			get
			{
				return this._lCHARCD;
			}
			set
			{
				this._lCHARCD = value;
			}
		}
		
		private string _lCHARNAME;
		public virtual string LCHARNAME
		{
			get
			{
				return this._lCHARNAME;
			}
			set
			{
				this._lCHARNAME = value;
			}
		}
		
		private int? _vALUE_;
		public virtual int? VALUE_
		{
			get
			{
				return this._vALUE_;
			}
			set
			{
				this._vALUE_ = value;
			}
		}
		
		private string _vALUEDESC;
		public virtual string VALUEDESC
		{
			get
			{
				return this._vALUEDESC;
			}
			set
			{
				this._vALUEDESC = value;
			}
		}
		
		private DateTime? _dATE_;
		public virtual DateTime? DATE_
		{
			get
			{
				return this._dATE_;
			}
			set
			{
				this._dATE_ = value;
			}
		}
		
	}
}
#pragma warning restore 1591
