#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace aConverterClassLibrary.RecordsDataAccessORM	
{
	public partial class NACH
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _lSHET;
		public virtual string LSHET
		{
			get
			{
				return this._lSHET;
			}
			set
			{
				this._lSHET = value;
			}
		}
		
		private string _dOCUMENTCD;
		public virtual string DOCUMENTCD
		{
			get
			{
				return this._dOCUMENTCD;
			}
			set
			{
				this._dOCUMENTCD = value;
			}
		}
		
		private int _mONTH_;
		public virtual int MONTH_
		{
			get
			{
				return this._mONTH_;
			}
			set
			{
				this._mONTH_ = value;
			}
		}
		
		private int _yEAR_;
		public virtual int YEAR_
		{
			get
			{
				return this._yEAR_;
			}
			set
			{
				this._yEAR_ = value;
			}
		}
		
		private int _mONTH2;
		public virtual int MONTH2
		{
			get
			{
				return this._mONTH2;
			}
			set
			{
				this._mONTH2 = value;
			}
		}
		
		private int _yEAR2;
		public virtual int YEAR2
		{
			get
			{
				return this._yEAR2;
			}
			set
			{
				this._yEAR2 = value;
			}
		}
		
		private decimal _fNATH;
		public virtual decimal FNATH
		{
			get
			{
				return this._fNATH;
			}
			set
			{
				this._fNATH = value;
			}
		}
		
		private decimal _pROCHL;
		public virtual decimal PROCHL
		{
			get
			{
				return this._pROCHL;
			}
			set
			{
				this._pROCHL = value;
			}
		}
		
		private decimal _vOLUME;
		public virtual decimal VOLUME
		{
			get
			{
				return this._vOLUME;
			}
			set
			{
				this._vOLUME = value;
			}
		}
		
		private int _rEGIMCD;
		public virtual int REGIMCD
		{
			get
			{
				return this._rEGIMCD;
			}
			set
			{
				this._rEGIMCD = value;
			}
		}
		
		private string _rEGIMNAME;
		public virtual string REGIMNAME
		{
			get
			{
				return this._rEGIMNAME;
			}
			set
			{
				this._rEGIMNAME = value;
			}
		}
		
		private int _sERVICECD;
		public virtual int SERVICECD
		{
			get
			{
				return this._sERVICECD;
			}
			set
			{
				this._sERVICECD = value;
			}
		}
		
		private string _sERVICENAM;
		public virtual string SERVICENAM
		{
			get
			{
				return this._sERVICENAM;
			}
			set
			{
				this._sERVICENAM = value;
			}
		}
		
		private DateTime _dATE_VV;
		public virtual DateTime DATE_VV
		{
			get
			{
				return this._dATE_VV;
			}
			set
			{
				this._dATE_VV = value;
			}
		}
		
		private int _tYPE_;
		public virtual int TYPE_
		{
			get
			{
				return this._tYPE_;
			}
			set
			{
				this._tYPE_ = value;
			}
		}
		
		private string _dOCNAME;
		public virtual string DOCNAME
		{
			get
			{
				return this._dOCNAME;
			}
			set
			{
				this._dOCNAME = value;
			}
		}
		
		private string _dOCNUMBER;
		public virtual string DOCNUMBER
		{
			get
			{
				return this._dOCNUMBER;
			}
			set
			{
				this._dOCNUMBER = value;
			}
		}
		
		private DateTime? _dOCDATE;
		public virtual DateTime? DOCDATE
		{
			get
			{
				return this._dOCDATE;
			}
			set
			{
				this._dOCDATE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
