#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace aConverterClassLibrary.RecordsDataAccessORM	
{
	public partial class STREET
	{
		private int _sTREETCD;
		public virtual int STREETCD
		{
			get
			{
				return this._sTREETCD;
			}
			set
			{
				this._sTREETCD = value;
			}
		}
		
		private int _pUNKTCD;
		public virtual int PUNKTCD
		{
			get
			{
				return this._pUNKTCD;
			}
			set
			{
				this._pUNKTCD = value;
			}
		}
		
		private string _sTREETNM;
		public virtual string STREETNM
		{
			get
			{
				return this._sTREETNM;
			}
			set
			{
				this._sTREETNM = value;
			}
		}
		
		private string _nOTE;
		public virtual string NOTE
		{
			get
			{
				return this._nOTE;
			}
			set
			{
				this._nOTE = value;
			}
		}
		
		private string _kLADR;
		public virtual string KLADR
		{
			get
			{
				return this._kLADR;
			}
			set
			{
				this._kLADR = value;
			}
		}
		
		private string _oKATO;
		public virtual string OKATO
		{
			get
			{
				return this._oKATO;
			}
			set
			{
				this._oKATO = value;
			}
		}
		
		private string _sOCR;
		public virtual string SOCR
		{
			get
			{
				return this._sOCR;
			}
			set
			{
				this._sOCR = value;
			}
		}
		
	}
}
#pragma warning restore 1591
