SET TERM ^ ;

create or alter procedure CNV$CNV_01100_COUNTERTYPES
as
begin
    INSERT INTO COUNTERSTYPES (KOD, EQUIPMENTTYPEID, PERIODKOD, NAME, COEFFICIENT, DIGITCOUNT, EQUIPMENTGROUPID, EXTORGCD, DIMENSIONTYPE, MINCONSUMPTION, MAXCONSUMPTION, MINTEMPERATURE, MAXTEMPERATURE, COUNTERMARKMODULEID, SERVICELIFEID, ACCURACY)
    select ID, EQUIPMENTTYPEID, PERIODKOD, NAME, COEFFICIENT, DIGITCOUNT, EQUIPMENTGROUPID, EXTORGCD, DIMENSIONTYPE, MINCONSUMPTION, MAXCONSUMPTION, MINTEMPERATURE, MAXTEMPERATURE, COUNTERMARKMODULEID, SERVICELIFEID, ACCURACY
    from cnv$countertypes cct;

    EXECUTE STATEMENT 'ALTER SEQUENCE COUNTERSTYPES_G RESTART WITH ' || (select max(kod) + 1 from counterstypes);
end^

SET TERM ; ^