SET TERM ^ ;

create or alter procedure CNV$CNV_02150_MASSEXTLSHETS
as
BEGIN
	INSERT INTO EXTORGSPR (EXTORGCD, EXTORGNM, CANGIVELGOT, PAYIMPORT, CHARSIMPORT, ISACCOUNT, LSHETFORMAT, HASOWNADRESSCD, EQUIPMENTSALE, EQUIPMENTMAKE, ISPROVIDER, JURIDICALADDRESS, POSTADDRESS, PHONE, INN, KPP, RS, DIRECTOR, MAINACCOUNTANT, NOTE, OKPO, BANK, KORACCOUNT, BIK, ISEXTERNALCALC, CANISSUEPASSP, ISBASEORGANIZATION, SECTORADDRESS, SECTORPHONE, SECTORWORKMODE, ISDEFAULTORG, ISMILITARYCOMISSION, ISTAX, ISREGISTRATIONAUTHORITY, DEPARTMENTCD, EMAIL, ISMANAGMENTCOMPANY, OGRN, EXPORTTOPAYSYSTEM, ISALTERNATIVEACCOUNT, EXTORGROLEGISZKHID, BIK_BN, RS_BN, AUTODROPEXTLSHETS)
	select ecd.extorgcd,
		(select first 1 ce.extorgname
		from cnv$extlshet ce
		where ce.extorgcd = ecd.extorgcd),
		0, 0, 0, 1, null, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, 1
	from (
		select distinct ce.extorgcd
		from cnv$extlshet ce
		left join extorgspr eo on eo.extorgcd = ce.extorgcd
		where eo.extorgcd is null
	) ecd;
	
	INSERT INTO EXTORGACCOUNTS (EXTORGCD, LSHET, EXTLSHET)
	select ce.extorgcd, ce.lshet, ce.extlshet
	from cnv$extlshet ce;
END^

SET TERM ; ^