SET TERM ^ ;	
create or alter procedure CNV$CNV_03400_ABONENTCONTRACTS
as
declare variable LSHET varchar(10);
declare variable NAME varchar(150);
declare variable TYPEID integer;
declare variable DOC_SER varchar(20);
declare variable DOC_NUMBER varchar(150);
declare variable DOC_DATE timestamp;
declare variable ORGID integer;
declare variable STARTDATE timestamp;
declare variable ENDDATE timestamp;
declare variable PRIM varchar(1000);
declare variable CITIZENID integer;
declare variable SERVICES varchar(150);
declare variable SINGLESERVICE VARCHAR(10);
declare variable DOCUMENTCD INTEGER;
begin
    FOR SELECT CA.LSHET, CA.NAME, CA.TYPEID, CA.DOC_SER, CA.DOC_NUMBER, CA.DOC_DATE, CA.ORGID, CA.STARTDATE, CA.ENDDATE, CA.PRIM, CA.CITIZENID, CA.SERVICES
        FROM CNV$ABONENTCONTRACT CA
    INTO :LSHET, :NAME, :TYPEID, :DOC_SER, :DOC_NUMBER, :DOC_DATE, :ORGID, :STARTDATE, :ENDDATE, :PRIM, :CITIZENID, :SERVICES
    DO BEGIN
        DOCUMENTCD = (SELECT GEN_ID(DOCUMENTS_GEN, 1) FROM RDB$DATABASE);
        INSERT INTO DOCUMENTS (DOCUMENTCD, ORGANIZATIONCD, REGISTERUSERCD, OTVETSTVUSERCD, DOCTYPEID, DOCNAME, DOC_NUMBER, DOC_SER, DOCDATE, INPUTDATE, OUTPUTDATE)
            VALUES (:DOCUMENTCD, :ORGID, 1, 1, :TYPEID, :NAME, :DOC_NUMBER, :DOC_SER, :DOC_DATE, :STARTDATE, :ENDDATE);
        INSERT INTO ABONENTSCONTRACT (DOCUMENTCD, LSHET, STARTDATE, FINISHDATE, SERVICEID, DESCRIPTION, CITYZEN_ID, EXTORGCD)
            VALUES (:DOCUMENTCD, :LSHET, :STARTDATE, :ENDDATE, NULL, :PRIM, :CITIZENID, NULL);
        FOR SELECT SPLITVALUE FROM SPLIT(:SERVICES, ';') INTO :SINGLESERVICE
        DO BEGIN
            INSERT INTO DOCUMENTBALANCES (DOCUMENTCD, BALANCE_KOD) VALUES (:DOCUMENTCD, :SINGLESERVICE);
        END
    END
end^

SET TERM ; ^