CREATE TABLE CNV$PENISUMMA (
  ID INTEGER NOT NULL,
  SERVICECD INTEGER,
  LSHET VARCHAR(10),
  FDATE Timestamp,
  FDAY integer,
  FMONTH integer,
  FYEAR integer,
  ABONENTSALDO numeric(18,4),
  PENINACHISLSUMMA numeric(18,4),
  ISCONTROLPOINT integer,
  NDATE timestamp,
  IZMEN integer,
  PRIMARY KEY (ID)
);
CREATE INDEX CNV$PENISUMMA_IDX1 ON CNV$PENISUMMA (LSHET);
CREATE SEQUENCE GEN_CNV$PENISUMMA_ID;

SET TERM ^ ;
CREATE TRIGGER CNV$PENISUMMA_BI FOR CNV$PENISUMMA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CNV$PENISUMMA_ID,1);
END
^
SET TERM ; ^
