CREATE TABLE CNV$LCHARHOUSES (
  ID INTEGER NOT NULL,
  HOUSECD INTEGER,
  LCHARCD INTEGER,
  LCHARNAME varchar(100),
  VALUE_ INTEGER,
  VALUEDESC varchar(100),
  DATE_ TIMESTAMP,
  PRIMARY KEY (ID)
);
CREATE SEQUENCE GEN_CNV$LCHARHOUSES_ID;

SET TERM ^ ;
CREATE TRIGGER CNV$LCHARHOUSES_BI FOR CNV$LCHARHOUSES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CNV$LCHARHOUSES_ID,1);
END
^
SET TERM ; ^
