CREATE TABLE CNV$CHARLST (
    ID INTEGER NOT NULL,
    ADDCHARCD    INTEGER,
    ADDCHARNAME  VARCHAR(50),
    ADDCHTYPE    SMALLINT,
    ADDCHARMODE  SMALLINT,
    SHORTNAME    VARCHAR(50)
);
CREATE INDEX CNV$CHARLST_IDX1 ON CNV$CHARLST (ADDCHARCD);
CREATE SEQUENCE GEN_CNV$CHARLST_ID;

SET TERM ^ ;
CREATE TRIGGER CNV$CHARLST_BI FOR CNV$CHARLST
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CNV$CHARLST_ID,1);
END
^
SET TERM ; ^

