CREATE TABLE CNV$ADDDCHAR (
    ID INTEGER NOT NULL,
    LSHET VARCHAR(10),
    ADDCHARCD INTEGER,
    "VALUE" VARCHAR(30),
    primary key (ID));
CREATE INDEX CNV$ADDDCHAR_IDX1 ON CNV$ADDDCHAR (LSHET);
CREATE SEQUENCE GEN_CNV$ADDDCHAR_ID;

SET TERM ^ ;
CREATE TRIGGER CNV$ADDDCHAR_BI FOR CNV$ADDDCHAR
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CNV$ADDDCHAR_ID,1);
END
^
SET TERM ; ^

