CREATE TABLE CNV$AADDCHAR (
    ID INTEGER NOT NULL,
    LSHET VARCHAR(10),
    ADDCHARCD INTEGER,
    "VALUE" VARCHAR(30),
    primary key (ID));
CREATE INDEX CNV$AADDCHAR_IDX1 ON CNV$AADDCHAR (LSHET);
CREATE SEQUENCE GEN_CNV$AADDCHAR_ID;

SET TERM ^ ;
CREATE TRIGGER CNV$AADDCHAR_BI FOR CNV$AADDCHAR
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CNV$AADDCHAR_ID,1);
END
^
SET TERM ; ^

