CREATE TABLE CNV$LCHARS (
  ID INTEGER NOT NULL,
  LSHET varchar(10),
  LCHARCD INTEGER,
  LCHARNAME varchar(100),
  VALUE_ INTEGER,
  VALUEDESC varchar(100),
  DATE_ TIMESTAMP,
  PRIMARY KEY (ID)
);
CREATE INDEX CNV$LCHARS_IDX1 ON CNV$LCHARS (LSHET);
CREATE SEQUENCE GEN_CNV$LCHARS_ID;

SET TERM ^ ;
CREATE TRIGGER CNV$LCHARS_BI FOR CNV$LCHARS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CNV$LCHARS_ID,1);
END
^
SET TERM ; ^
