CREATE TABLE CNV$ABONENTPHONES (
	ID INTEGER NOT NULL,
	LSHET VARCHAR(10),
	TYPEID INTEGER,
	PHONENUMBER VARCHAR(100),
	PRIMARY KEY (ID));
	
CREATE INDEX CNV$ABONENTPHONES_IDX1 ON CNV$ABONENTPHONES (LSHET);
CREATE SEQUENCE GEN_CNV$ABONENTPHONES_ID;

SET TERM ^ ;
CREATE TRIGGER CNV$ABONENTPHONES_BI FOR CNV$ABONENTPHONES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CNV$ABONENTPHONES_ID,1);
END
^
SET TERM ; ^
