CREATE TABLE CNV$CHECKCASESPDESC (
    ID           INTEGER NOT NULL,
    NAME         VARCHAR(30),
    DESCRIPTION  VARCHAR(200),
    NORMALROWS   INTEGER,
    RUNAFTER     INTEGER,
    CANTEST     SMALLINT NOT NULL,
    CANANALYZE   SMALLINT NOT NULL,
    CANFIX     SMALLINT NOT NULL,
    PROCTYPE	SMALLINT NOT NULL /* 0 - CheckCase, 1 - Convertation */
);
ALTER TABLE CNV$CHECKCASESPDESC ADD CONSTRAINT PK_CNV$CHECKCASESPDESC PRIMARY KEY (ID);
ALTER TABLE CNV$CHECKCASESPDESC ADD CONSTRAINT FK_CNV$CHECKCASESPDESC_1 FOREIGN KEY (RUNAFTER) REFERENCES CNV$CHECKCASESPDESC (ID);

INSERT INTO CNV$CHECKCASESPDESC (ID, NAME, DESCRIPTION, NORMALROWS, RUNAFTER, CANTEST, CANANALYZE, CANFIX) 
   VALUES (1, 'CNV$CC_LSHETLENGTH', 'Проверка соответствия формата лицевого счета (является ли лицевой счет в таблице ABONENT строкой одинаковой длины)', 1, NULL, 1, 1, 0);
INSERT INTO CNV$CHECKCASESPDESC (ID, NAME, DESCRIPTION, NORMALROWS, RUNAFTER, CANTEST, CANANALYZE, CANFIX) 
   VALUES (2, 'CNV$CC_NOTUNIQUELSHET', 'Проверка на уникальность лицевых счетов в таблице CNV$ABONENT', 0, 1, 1, 1, 0);
INSERT INTO CNV$CHECKCASESPDESC (ID, NAME, DESCRIPTION, NORMALROWS, RUNAFTER, CANTEST, CANANALYZE, CANFIX) 
   VALUES (3, 'CNV$CC_FIO', 'Проверяется, заполненны ли надлежащим образом поля F, I и O', 0, NULL, 1, 1, 0);
INSERT INTO CNV$CHECKCASESPDESC (ID, NAME, DESCRIPTION, NORMALROWS, RUNAFTER, CANTEST, CANANALYZE, CANFIX) 
   VALUES (4, 'CNV$CC_NOTUNIQUENACHOPLSALDO', 'Проверка, встречаются ли в таблице CNV$NACHOPL несколько записей по одному лицевому счету в одном месяце по одной услуге', 0, 2, 1, 1, 1);
INSERT INTO CNV$CHECKCASESPDESC (ID, NAME, DESCRIPTION, NORMALROWS, RUNAFTER, CANTEST, CANANALYZE, CANFIX) 
   VALUES (5, 'CNV_CC_SALDOHISTORYGAP', 'Проверка на "пропуски" в истории оплат/начислений', 0, 4, 1, 1, 1);
INSERT INTO CNV$CHECKCASESPDESC (ID, NAME, DESCRIPTION, NORMALROWS, RUNAFTER, CANTEST, CANANALYZE, CANFIX) 
   VALUES (6, 'CNV_CC_OLDNEWSALDOMISMATCH', 'Проверка, что для всех записей в истории оплат/начислений сальдо на конец месяца предыдущего равно салдо на начало следующего', 0, 5, 1, 1, 1);
INSERT INTO CNV$CHECKCASESPDESC (ID, NAME, DESCRIPTION, NORMALROWS, RUNAFTER, CANTEST, CANANALYZE, CANFIX) 
   VALUES (7, 'CNV_CC_FIRSTSALDOISNOTNULL', 'Проверка, что сальдо первой строки в истории оплат/начислений равно 0', 0, 4, 1, 1, 0);


