CREATE TABLE CNV$DOGOVOR (
  ID INTEGER NOT NULL,
  LSHET varchar(10),
  DOGTYPEKOD INTEGER,
  DOGTYPENAM varchar(50),
  DESCRIPTIO varchar(100),
  STARTDATE timestamp,
  ENDDATE timestamp,
  SERIA varchar(12),
  NOMER varchar(12),
  PRIMARY KEY (ID)
);
CREATE INDEX CNV$DOGOVOR_IDX1 ON CNV$DOGOVOR (LSHET);
CREATE SEQUENCE GEN_CNV$DOGOVOR_ID;

SET TERM ^ ;
CREATE TRIGGER CNV$DOGOVOR_BI FOR CNV$DOGOVOR
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CNV$DOGOVOR_ID,1);
END
^
SET TERM ; ^
