CREATE TABLE CNV$ABONENT (
  ID INTEGER NOT NULL,
  LSHET VARCHAR(10),
  HOUSECD INTEGER,
  DISTKOD INTEGER,
  DISTNAME VARCHAR(40),
  RAYONKOD INTEGER,
  RAYONNAME VARCHAR(40),
  TOWNSKOD INTEGER,
  TOWNSNAME VARCHAR(40),
  ULICAKOD INTEGER,
  ULICANAME VARCHAR(40),
  NDOMA VARCHAR(20),
  KORPUS INTEGER,
  KVARTIRA VARCHAR(10),
  KOMNATA INTEGER,
  F VARCHAR(50),
  I VARCHAR(50),
  O VARCHAR(50),
  PRIM_ VARCHAR(250),
  EXTLSHET VARCHAR(20),
  EXTLSHET2 VARCHAR(20),
  PHONENUM VARCHAR(100),
  POSTINDEX VARCHAR(6),
  DUCD INTEGER,
  DUNAME VARCHAR(50),
  ISDELETED INTEGER,
  PRIMARY KEY (ID)
);
CREATE INDEX CNV$ABONENT_IDX1 ON CNV$ABONENT (LSHET);

CREATE SEQUENCE GEN_CNV$ABONENT_ID;

SET TERM ^ ;

CREATE TRIGGER CNV$ABONENT_BI FOR CNV$ABONENT
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CNV$ABONENT_ID,1);
END
^

SET TERM ; ^




