/******************************************************************************/
/***               Generated by IBExpert 30.06.2015 20:37:48                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_CNV$ABONENT_ID;

CREATE TABLE CNV$ABONENT (
    ID             INTEGER NOT NULL,
    LSHET          VARCHAR(10),
    HOUSECD        INTEGER,
    DISTKOD        INTEGER,
    DISTNAME       VARCHAR(40),
    RAYONKOD       INTEGER,
    RAYONNAME      VARCHAR(40),
    TOWNSKOD       INTEGER,
    TOWNSNAME      VARCHAR(40),
    ULICAKOD       INTEGER,
    ULICANAME      VARCHAR(40),
    KVARTIRA       VARCHAR(10),
    KOMNATA        INTEGER,
    F              VARCHAR(50),
    I              VARCHAR(50),
    O              VARCHAR(50),
    PRIM_          VARCHAR(250),
    EXTLSHET       VARCHAR(20),
    EXTLSHET2      VARCHAR(20),
    PHONENUM       VARCHAR(100),
    POSTINDEX      VARCHAR(6),
    DUCD           INTEGER,
    DUNAME         VARCHAR(50),
    ISDELETED      INTEGER,
    HOUSENO        VARCHAR(10),
    HOUSEPOSTFIX   VARCHAR(10),
    KORPUSNO       INTEGER,
    KORPUSPOSTFIX  VARCHAR(10)
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE CNV$ABONENT ADD PRIMARY KEY (ID);


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX CNV$ABONENT_IDX1 ON CNV$ABONENT (LSHET);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: CNV$ABONENT_BI */
CREATE OR ALTER TRIGGER CNV$ABONENT_BI FOR CNV$ABONENT
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CNV$ABONENT_ID,1);
END
^


SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
