CREATE GENERATOR GEN_CNV$EXTLSHET_ID;

CREATE TABLE CNV$EXTLSHET (
    ID             INTEGER NOT NULL,
    LSHET          VARCHAR(10),
	EXTLSHET	   VARCHAR(20),
	EXTORGCD	   INTEGER,
	EXTORGNAME	   VARCHAR(100)
);

ALTER TABLE CNV$EXTLSHET ADD PRIMARY KEY (ID);

CREATE INDEX CNV$EXTLSHET_IDX1 ON CNV$EXTLSHET (LSHET);
CREATE INDEX CNV$EXTLSHET_IDX2 ON CNV$EXTLSHET (EXTORGCD);

SET TERM ^ ;
CREATE OR ALTER TRIGGER CNV$EXTLSHET_BI FOR CNV$EXTLSHET
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CNV$EXTLSHET_ID,1);
END^
SET TERM ; ^