CREATE TABLE CNV$CHARS (
  ID INTEGER NOT NULL,
  LSHET VARCHAR(10),
  CHARCD INTEGER,
  CHARNAME VARCHAR(50),
  VALUE_ NUMERIC(11,4),
  DATE_ TIMESTAMP,
  PRIMARY KEY (ID)
);
CREATE INDEX CNV$CHARS_IDX1 ON CNV$CHARS (LSHET);
CREATE SEQUENCE GEN_CNV$CHARS_ID;

SET TERM ^ ;
CREATE TRIGGER CNV$CHARS_BI FOR CNV$CHARS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CNV$CHARS_ID,1);
END
^
SET TERM ; ^
