CREATE TABLE CNV$NACHOPL (
  ID INTEGER NOT NULL,
  LSHET varchar(10) NOT NULL,
  MONTH_ INTEGER NOT NULL,
  YEAR_ INTEGER NOT NULL,
  MONTH2 INTEGER NOT NULL,
  YEAR2 INTEGER NOT NULL,
  BDEBET NUMERIC(18,4) NOT NULL,
  FNATH NUMERIC(18,4) NOT NULL,
  PROCHL NUMERIC(18,4) NOT NULL,
  OPLATA NUMERIC(18,2) NOT NULL,
  EDEBET NUMERIC(18,4) NOT NULL,
  SERVICECD INTEGER NOT NULL,
  SERVICENAME varchar(50) NOT NULL,
  PRIMARY KEY (ID)
);
CREATE INDEX CNV$NACHOPL_IDX1 ON CNV$NACHOPL (LSHET);
CREATE SEQUENCE GEN_CNV$NACHOPL_ID;

SET TERM ^ ;
CREATE TRIGGER CNV$NACHOPL_BI FOR CNV$NACHOPL
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CNV$NACHOPL_ID,1);
END
^
SET TERM ; ^
