CREATE TABLE CNV$COUNTERS (
  ID INTEGER NOT NULL,
  COUNTERID varchar(20),
  LSHET varchar(10),
  CNTTYPE INTEGER,
  CNTNAME varchar(50),
  SETUPDATE timestamp,
  SERIALNUM varchar(30),
  SETUPPLACE INTEGER,
  PLACE varchar(20),
  PLOMBDATE timestamp,
  PLOMBNAME varchar(40),
  LASTPOV timestamp,
  NEXTPOV timestamp,
  PRIM_ varchar(100),
  DEACTDATE timestamp,
  TAG varchar(30),
  NAME varchar(30),
  PRIMARY KEY (ID)
);
CREATE INDEX CNV$COUNTERS_IDX1 ON CNV$COUNTERS (LSHET);
CREATE SEQUENCE GEN_CNV$COUNTERS_ID;

SET TERM ^ ;
CREATE TRIGGER CNV$COUNTERS_BI FOR CNV$COUNTERS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CNV$COUNTERS_ID,1);
END
^
SET TERM ; ^
