CREATE TABLE CNV$CITYZENLGOTA (
  ID INTEGER NOT NULL,
  CITYZENID INTEGER NOT NULL,
  LGOTACD INTEGER NOT NULL,
  LGOTANAME VARCHAR(100),
  STARTDATE TIMESTAMP,
  ENDDATE TIMESTAMP,
  PRIORITY INTEGER,
  ISDELETED INTEGER, 
  PRIMARY KEY (ID)
);
CREATE INDEX CNV$CITYZENLGOTA_IDX1 ON CNV$CITYZENLGOTA (CITYZENID);
CREATE SEQUENCE GEN_CNV$CITYZENLGOTA_ID;

SET TERM ^ ;
CREATE TRIGGER CNV$CITYZENLGOTA_BI FOR CNV$CITYZENLGOTA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL or NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_CNV$CITYZENLGOTA_ID,1);
END
^
SET TERM ; ^
