CREATE TABLE CNV$CNTRSIND (
  ID INTEGER NOT NULL,
  COUNTERID varchar(20),
  DOCUMENTCD varchar(20),
  OLDIND NUMERIC(16,4),
  OB_EM NUMERIC(16,4),
  INDICATION NUMERIC(16,4),
  INDDATE TIMESTAMP,
  INDTYPE INTEGER,
  PRIMARY KEY (ID)
);
CREATE SEQUENCE GEN_CNV$CNTRSIND_ID;

SET TERM ^ ;
CREATE TRIGGER CNV$CNTRSIND_BI FOR CNV$CNTRSIND
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CNV$CNTRSIND_ID,1);
END
^
SET TERM ; ^
