CREATE TABLE CNV$ABONENTCONTRACT (
	ID INTEGER NOT NULL,
	LSHET VARCHAR(10),
	NAME VARCHAR(150),
	TYPEID INTEGER,
	DOC_SER VARCHAR(20),
	DOC_NUMBER VARCHAR(150),
	DOC_DATE TIMESTAMP,
	ORGID INTEGER,
	STARTDATE TIMESTAMP,
	ENDDATE TIMESTAMP,
	PRIM VARCHAR(1000),
	CITIZENID INTEGER,
	SERVICES VARCHAR(150), /* список услуг через ; */
	PRIMARY KEY (ID));
	
CREATE INDEX CNV$ABONENTCONTRACT_IDX1 ON CNV$ABONENTCONTRACT (LSHET);
CREATE SEQUENCE GEN_CNV$ABONENTCONTRACT_ID;

SET TERM ^ ;
CREATE TRIGGER CNV$ABONENTCONTRACT_BI FOR CNV$ABONENTCONTRACT
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CNV$ABONENTCONTRACT_ID,1);
END
^
SET TERM ; ^
