CREATE TABLE CNV$EQUIPMENT (
  ID INTEGER NOT NULL,
  LSHET varchar(10),
  GROUPKOD INTEGER,
  GROUPNAME varchar(50),
  MARKKOD INTEGER,
  MARKNAME varchar(50),
  SETUPDATE timestamp,
  SERIALNUM varchar(30),
  PRIMARY KEY (ID)
);
CREATE INDEX CNV$EQUIPMENT_IDX1 ON CNV$EQUIPMENT (LSHET);
CREATE SEQUENCE GEN_CNV$EQUIPMENT_ID;

SET TERM ^ ;
CREATE TRIGGER CNV$EQUIPMENT_BI FOR CNV$EQUIPMENT
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CNV$EQUIPMENT_ID,1);
END
^
SET TERM ; ^
