CREATE TABLE CNV$CITIZENS (
  ID INTEGER NOT NULL,
  LSHET varchar(10),
  CITIZENID INTEGER,
  F varchar(30),
  I varchar(20),
  O varchar(20),
  BIRTHDATE timestamp,
  STARTDATE timestamp,
  ENDDATE timestamp,
  LGOTA INTEGER,
  LGOTANAME varchar(100),
  DATWP timestamp,
  DATUP timestamp,
  DOCUMENTNAME varchar(50),
  DOCTYPEID INTEGER,
  SERIA varchar(20),
  NOMER varchar(50),
  DATDN timestamp,
  DORGNAME varchar(1000),
  DORGCD integer,
  KOLLG INTEGER,
  HOZ INTEGER,
  BIRTHPLACE varchar(50),
  SOB INTEGER,
  DOLYA NUMERIC(9,2),
  COMMENT_ varchar(1000),
  PRIBYT varchar(100),
  VREMREG varchar(100),
  SEX integer,
  STATUSID integer,
  STATUSDATE timestamp,
  OWNERSHIPTYPE integer,
  OWNERSHIPNUMERATOR INTEGER,
  OWNERSHIPDENOMINATOR INTEGER,
  BIRTHCOUNTRY VARCHAR(500),
  BIRTHDISTRICT VARCHAR(500),
  BIRTHREGION VARCHAR(500),
  BIRTHCITY VARCHAR(500),
  BIRTHVILLAGE VARCHAR(500),
  CITIZENSHIP integer,
  ISMAINCITYZEN INTEGER NOT NULL,
  HIDDEN INTEGER NOT NULL,
  REGISTRATIONTYPE INTEGER NOT NULL,
  ARRIVEDATE TIMESTAMP,
  LEAVEDATE TIMESTAMP,
  LEAVECASEID INTEGER,
  DEATHDATE TIMESTAMP,
  EGRPNUMBER varchar(100),
  EGRPDATE TIMESTAMP,
  UNIQUECITIZENID varchar(45),
  PRIMARY KEY (ID)
);
CREATE INDEX CNV$CITIZENS_IDX1 ON CNV$CITIZENS (LSHET);
CREATE INDEX CNV$CITIZENS_IDX2 ON CNV$CITIZENS (UNIQUECITIZENID);
CREATE SEQUENCE GEN_CNV$CITIZENS_ID;

SET TERM ^ ;
CREATE TRIGGER CNV$CITIZENS_BI FOR CNV$CITIZENS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CNV$CITIZENS_ID,1);
END
^
SET TERM ; ^
