CREATE TABLE CNV$CONTRACTADDCHAR (
  ID INTEGER NOT NULL,
  CONTRACTID INTEGER,
  ADDCHARCD INTEGER,
  VALUE_ varchar(2000),
  PRIMARY KEY (ID)
);
CREATE SEQUENCE GEN_CNV$CONTRACTADDCHAR_ID;
CREATE INDEX CNV$CONTRACTADDCHAR_IDX1 ON CNV$CONTRACTADDCHAR (CONTRACTID);

SET TERM ^ ;
CREATE TRIGGER CNV$CONTRACTADDCHAR_BI FOR CNV$CONTRACTADDCHAR
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CNV$CONTRACTADDCHAR_ID,1);
END
^
SET TERM ; ^
