CREATE TABLE CNV$HADDCHAR (
  ID INTEGER NOT NULL,
  HOUSECD INTEGER,
  ADDCHARCD INTEGER,
  VALUE_ varchar(30),
  DATE_ timestamp,
  PRIMARY KEY (ID)
);
CREATE SEQUENCE GEN_CNV$HADDCHAR_ID;

SET TERM ^ ;
CREATE TRIGGER CNV$HADDCHAR_BI FOR CNV$HADDCHAR
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CNV$HADDCHAR_ID,1);
END
^
SET TERM ; ^
