#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using _037_COKPToVodokanal;

namespace _037_COKPToVodokanal	
{
	public partial class ABONENTPHONE
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _lSHET;
		public virtual string LSHET
		{
			get
			{
				return this._lSHET;
			}
			set
			{
				this._lSHET = value;
			}
		}
		
		private int? _pHONETYPEID;
		public virtual int? PHONETYPEID
		{
			get
			{
				return this._pHONETYPEID;
			}
			set
			{
				this._pHONETYPEID = value;
			}
		}
		
		private string _pHONENUMBER;
		public virtual string PHONENUMBER
		{
			get
			{
				return this._pHONENUMBER;
			}
			set
			{
				this._pHONENUMBER = value;
			}
		}
		
		private ABONENT _aBONENT;
		public virtual ABONENT ABONENT
		{
			get
			{
				return this._aBONENT;
			}
			set
			{
				this._aBONENT = value;
			}
		}
		
	}
}
#pragma warning restore 1591
