#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace _037_COKPToVodokanal	
{
	public partial class GT_COUNTER
	{
		private string _lSHET;
		public virtual string LSHET
		{
			get
			{
				return this._lSHET;
			}
			set
			{
				this._lSHET = value;
			}
		}
		
		private string _eQUIPMENTIDENTIFIER;
		public virtual string EQUIPMENTIDENTIFIER
		{
			get
			{
				return this._eQUIPMENTIDENTIFIER;
			}
			set
			{
				this._eQUIPMENTIDENTIFIER = value;
			}
		}
		
		private int _cOUNTERCD;
		public virtual int COUNTERCD
		{
			get
			{
				return this._cOUNTERCD;
			}
			set
			{
				this._cOUNTERCD = value;
			}
		}
		
		private string _cOUNTERNAME;
		public virtual string COUNTERNAME
		{
			get
			{
				return this._cOUNTERNAME;
			}
			set
			{
				this._cOUNTERNAME = value;
			}
		}
		
		private string _sERIALNUMBER;
		public virtual string SERIALNUMBER
		{
			get
			{
				return this._sERIALNUMBER;
			}
			set
			{
				this._sERIALNUMBER = value;
			}
		}
		
		private DateTime? _rELEASEDATE;
		public virtual DateTime? RELEASEDATE
		{
			get
			{
				return this._rELEASEDATE;
			}
			set
			{
				this._rELEASEDATE = value;
			}
		}
		
		private DateTime? _sALEDATE;
		public virtual DateTime? SALEDATE
		{
			get
			{
				return this._sALEDATE;
			}
			set
			{
				this._sALEDATE = value;
			}
		}
		
		private DateTime? _sETUPDATE;
		public virtual DateTime? SETUPDATE
		{
			get
			{
				return this._sETUPDATE;
			}
			set
			{
				this._sETUPDATE = value;
			}
		}
		
		private DateTime? _gUARANTEEENDDATE;
		public virtual DateTime? GUARANTEEENDDATE
		{
			get
			{
				return this._gUARANTEEENDDATE;
			}
			set
			{
				this._gUARANTEEENDDATE = value;
			}
		}
		
		private int? _mAXGUARANTEEPERIOD;
		public virtual int? MAXGUARANTEEPERIOD
		{
			get
			{
				return this._mAXGUARANTEEPERIOD;
			}
			set
			{
				this._mAXGUARANTEEPERIOD = value;
			}
		}
		
		private int? _mARKCD;
		public virtual int? MARKCD
		{
			get
			{
				return this._mARKCD;
			}
			set
			{
				this._mARKCD = value;
			}
		}
		
		private string _mARKNAME;
		public virtual string MARKNAME
		{
			get
			{
				return this._mARKNAME;
			}
			set
			{
				this._mARKNAME = value;
			}
		}
		
		private int? _cOUNTER_LEVEL;
		public virtual int? COUNTER_LEVEL
		{
			get
			{
				return this._cOUNTER_LEVEL;
			}
			set
			{
				this._cOUNTER_LEVEL = value;
			}
		}
		
		private int? _dIGITCOUNT;
		public virtual int? DIGITCOUNT
		{
			get
			{
				return this._dIGITCOUNT;
			}
			set
			{
				this._dIGITCOUNT = value;
			}
		}
		
		private string _dIMENSIONTYPE;
		public virtual string DIMENSIONTYPE
		{
			get
			{
				return this._dIMENSIONTYPE;
			}
			set
			{
				this._dIMENSIONTYPE = value;
			}
		}
		
		private decimal? _mINCONSUMPTION;
		public virtual decimal? MINCONSUMPTION
		{
			get
			{
				return this._mINCONSUMPTION;
			}
			set
			{
				this._mINCONSUMPTION = value;
			}
		}
		
		private decimal? _mAXCONSUMPTION;
		public virtual decimal? MAXCONSUMPTION
		{
			get
			{
				return this._mAXCONSUMPTION;
			}
			set
			{
				this._mAXCONSUMPTION = value;
			}
		}
		
		private decimal? _mINTEMPERATURE;
		public virtual decimal? MINTEMPERATURE
		{
			get
			{
				return this._mINTEMPERATURE;
			}
			set
			{
				this._mINTEMPERATURE = value;
			}
		}
		
		private decimal? _mAXTEMPERATURE;
		public virtual decimal? MAXTEMPERATURE
		{
			get
			{
				return this._mAXTEMPERATURE;
			}
			set
			{
				this._mAXTEMPERATURE = value;
			}
		}
		
		private int? _pERIODPPRCD;
		public virtual int? PERIODPPRCD
		{
			get
			{
				return this._pERIODPPRCD;
			}
			set
			{
				this._pERIODPPRCD = value;
			}
		}
		
		private string _pERIODPPRNAME;
		public virtual string PERIODPPRNAME
		{
			get
			{
				return this._pERIODPPRNAME;
			}
			set
			{
				this._pERIODPPRNAME = value;
			}
		}
		
		private int? _pERIODPPRYEAR;
		public virtual int? PERIODPPRYEAR
		{
			get
			{
				return this._pERIODPPRYEAR;
			}
			set
			{
				this._pERIODPPRYEAR = value;
			}
		}
		
		private int? _pERIODPPRMONTH;
		public virtual int? PERIODPPRMONTH
		{
			get
			{
				return this._pERIODPPRMONTH;
			}
			set
			{
				this._pERIODPPRMONTH = value;
			}
		}
		
		private int? _pERIODPPRDAY;
		public virtual int? PERIODPPRDAY
		{
			get
			{
				return this._pERIODPPRDAY;
			}
			set
			{
				this._pERIODPPRDAY = value;
			}
		}
		
		private DateTime? _dATEPPR;
		public virtual DateTime? DATEPPR
		{
			get
			{
				return this._dATEPPR;
			}
			set
			{
				this._dATEPPR = value;
			}
		}
		
		private DateTime? _pLOMBDATE;
		public virtual DateTime? PLOMBDATE
		{
			get
			{
				return this._pLOMBDATE;
			}
			set
			{
				this._pLOMBDATE = value;
			}
		}
		
		private string _pLOMBNUMBER;
		public virtual string PLOMBNUMBER
		{
			get
			{
				return this._pLOMBNUMBER;
			}
			set
			{
				this._pLOMBNUMBER = value;
			}
		}
		
		private decimal? _rECOUNTKOEFFICIENT;
		public virtual decimal? RECOUNTKOEFFICIENT
		{
			get
			{
				return this._rECOUNTKOEFFICIENT;
			}
			set
			{
				this._rECOUNTKOEFFICIENT = value;
			}
		}
		
		private int? _sTATUSCD;
		public virtual int? STATUSCD
		{
			get
			{
				return this._sTATUSCD;
			}
			set
			{
				this._sTATUSCD = value;
			}
		}
		
		private DateTime? _sTATUSDATE;
		public virtual DateTime? STATUSDATE
		{
			get
			{
				return this._sTATUSDATE;
			}
			set
			{
				this._sTATUSDATE = value;
			}
		}
		
		private string _sTATUSNAME;
		public virtual string STATUSNAME
		{
			get
			{
				return this._sTATUSNAME;
			}
			set
			{
				this._sTATUSNAME = value;
			}
		}
		
		private int? _iSDEFAULT;
		public virtual int? ISDEFAULT
		{
			get
			{
				return this._iSDEFAULT;
			}
			set
			{
				this._iSDEFAULT = value;
			}
		}
		
		private DateTime? _iNDICATIONDATE;
		public virtual DateTime? INDICATIONDATE
		{
			get
			{
				return this._iNDICATIONDATE;
			}
			set
			{
				this._iNDICATIONDATE = value;
			}
		}
		
		private decimal? _iNDICATIONVALUE;
		public virtual decimal? INDICATIONVALUE
		{
			get
			{
				return this._iNDICATIONVALUE;
			}
			set
			{
				this._iNDICATIONVALUE = value;
			}
		}
		
		private int? _iNDICATIONCD;
		public virtual int? INDICATIONCD
		{
			get
			{
				return this._iNDICATIONCD;
			}
			set
			{
				this._iNDICATIONCD = value;
			}
		}
		
		private int? _sERVICEMASTERID;
		public virtual int? SERVICEMASTERID
		{
			get
			{
				return this._sERVICEMASTERID;
			}
			set
			{
				this._sERVICEMASTERID = value;
			}
		}
		
		private int? _sERVICEID;
		public virtual int? SERVICEID
		{
			get
			{
				return this._sERVICEID;
			}
			set
			{
				this._sERVICEID = value;
			}
		}
		
		private string _nOTE;
		public virtual string NOTE
		{
			get
			{
				return this._nOTE;
			}
			set
			{
				this._nOTE = value;
			}
		}
		
		private DateTime? _cONTROL_INDICATIONDATE;
		public virtual DateTime? CONTROL_INDICATIONDATE
		{
			get
			{
				return this._cONTROL_INDICATIONDATE;
			}
			set
			{
				this._cONTROL_INDICATIONDATE = value;
			}
		}
		
		private decimal? _cONTROL_INDICATIONVALUE;
		public virtual decimal? CONTROL_INDICATIONVALUE
		{
			get
			{
				return this._cONTROL_INDICATIONVALUE;
			}
			set
			{
				this._cONTROL_INDICATIONVALUE = value;
			}
		}
		
		private int? _cONTROL_INDICATIONCD;
		public virtual int? CONTROL_INDICATIONCD
		{
			get
			{
				return this._cONTROL_INDICATIONCD;
			}
			set
			{
				this._cONTROL_INDICATIONCD = value;
			}
		}
		
		private DateTime? _nON_CONTROL_INDICATIONDATE;
		public virtual DateTime? NON_CONTROL_INDICATIONDATE
		{
			get
			{
				return this._nON_CONTROL_INDICATIONDATE;
			}
			set
			{
				this._nON_CONTROL_INDICATIONDATE = value;
			}
		}
		
		private decimal? _nON_CONTROL_INDICATIONVALUE;
		public virtual decimal? NON_CONTROL_INDICATIONVALUE
		{
			get
			{
				return this._nON_CONTROL_INDICATIONVALUE;
			}
			set
			{
				this._nON_CONTROL_INDICATIONVALUE = value;
			}
		}
		
		private int? _nON_CONTROL_INDICATIONCD;
		public virtual int? NON_CONTROL_INDICATIONCD
		{
			get
			{
				return this._nON_CONTROL_INDICATIONCD;
			}
			set
			{
				this._nON_CONTROL_INDICATIONCD = value;
			}
		}
		
		private DateTime? _nEXTDATEPPR;
		public virtual DateTime? NEXTDATEPPR
		{
			get
			{
				return this._nEXTDATEPPR;
			}
			set
			{
				this._nEXTDATEPPR = value;
			}
		}
		
		private int? _rESOURCE_KOD;
		public virtual int? RESOURCE_KOD
		{
			get
			{
				return this._rESOURCE_KOD;
			}
			set
			{
				this._rESOURCE_KOD = value;
			}
		}
		
		private int? _tYPEKOD;
		public virtual int? TYPEKOD
		{
			get
			{
				return this._tYPEKOD;
			}
			set
			{
				this._tYPEKOD = value;
			}
		}
		
		private int? _eXTORGCD;
		public virtual int? EXTORGCD
		{
			get
			{
				return this._eXTORGCD;
			}
			set
			{
				this._eXTORGCD = value;
			}
		}
		
		private int? _eQUIPMENTGROUPID;
		public virtual int? EQUIPMENTGROUPID
		{
			get
			{
				return this._eQUIPMENTGROUPID;
			}
			set
			{
				this._eQUIPMENTGROUPID = value;
			}
		}
		
		private string _eQUIPMENTGROUPNAME;
		public virtual string EQUIPMENTGROUPNAME
		{
			get
			{
				return this._eQUIPMENTGROUPNAME;
			}
			set
			{
				this._eQUIPMENTGROUPNAME = value;
			}
		}
		
		private int? _cOUNTERPLACE;
		public virtual int? COUNTERPLACE
		{
			get
			{
				return this._cOUNTERPLACE;
			}
			set
			{
				this._cOUNTERPLACE = value;
			}
		}
		
		private int? _iNSPECTMODE;
		public virtual int? INSPECTMODE
		{
			get
			{
				return this._iNSPECTMODE;
			}
			set
			{
				this._iNSPECTMODE = value;
			}
		}
		
		private int? _tARGETBALANCE_KOD;
		public virtual int? TARGETBALANCE_KOD
		{
			get
			{
				return this._tARGETBALANCE_KOD;
			}
			set
			{
				this._tARGETBALANCE_KOD = value;
			}
		}
		
		private int? _uNITINGID;
		public virtual int? UNITINGID
		{
			get
			{
				return this._uNITINGID;
			}
			set
			{
				this._uNITINGID = value;
			}
		}
		
		private short? _iSMULTISCALE;
		public virtual short? ISMULTISCALE
		{
			get
			{
				return this._iSMULTISCALE;
			}
			set
			{
				this._iSMULTISCALE = value;
			}
		}
		
		private short? _iSMAINMULTISCALE;
		public virtual short? ISMAINMULTISCALE
		{
			get
			{
				return this._iSMAINMULTISCALE;
			}
			set
			{
				this._iSMAINMULTISCALE = value;
			}
		}
		
		private int? _oLDCOUNTERCD;
		public virtual int? OLDCOUNTERCD
		{
			get
			{
				return this._oLDCOUNTERCD;
			}
			set
			{
				this._oLDCOUNTERCD = value;
			}
		}
		
		private int? _eXTBALANCE_KOD;
		public virtual int? EXTBALANCE_KOD
		{
			get
			{
				return this._eXTBALANCE_KOD;
			}
			set
			{
				this._eXTBALANCE_KOD = value;
			}
		}
		
	}
}
#pragma warning restore 1591
