//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aConverterClassLibrary.RecordsEDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConverterdbEntities : DbContext
    {
        public ConverterdbEntities()
            : base("name=ConverterdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<aaddchar> aaddchars { get; set; }
        public DbSet<abonent> abonents { get; set; }
        public DbSet<charlst> charlsts { get; set; }
        public DbSet<@char> chars { get; set; }
        public DbSet<charval> charvals { get; set; }
        public DbSet<cntrsind> cntrsinds { get; set; }
        public DbSet<counter> counters { get; set; }
        public DbSet<dogovor> dogovors { get; set; }
        public DbSet<equipmnt> equipmnts { get; set; }
        public DbSet<gcounter> gcounters { get; set; }
        public DbSet<haddchar> haddchars { get; set; }
        public DbSet<lchar> lchars { get; set; }
        public DbSet<lgota> lgotas { get; set; }
        public DbSet<nach> naches { get; set; }
        public DbSet<nachopl> nachopls { get; set; }
        public DbSet<oplata> oplatas { get; set; }
        public DbSet<supplnet> supplnets { get; set; }
    }
}
