#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using _027_COKPToVodokanal;

namespace _027_COKPToVodokanal	
{
	public partial class AbonentEntitiesModel : OpenAccessContext, IAbonentEntitiesModelUnitOfWork
	{
		private static string connectionStringName = @"Connection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("AbonentEntitiesModel.rlinq");
		
		public AbonentEntitiesModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public AbonentEntitiesModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public AbonentEntitiesModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public AbonentEntitiesModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public AbonentEntitiesModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<STREET> STREETs 
		{
			get
			{
				return this.GetAll<STREET>();
			}
		}
		
		public IQueryable<LCHARSLIST> LCHARSLISTs 
		{
			get
			{
				return this.GetAll<LCHARSLIST>();
			}
		}
		
		public IQueryable<LCHARSABONENTLIST> LCHARSABONENTLISTs 
		{
			get
			{
				return this.GetAll<LCHARSABONENTLIST>();
			}
		}
		
		public IQueryable<HOUSE> HOUSEs 
		{
			get
			{
				return this.GetAll<HOUSE>();
			}
		}
		
		public IQueryable<GT_COUNTER> GT_COUNTERs 
		{
			get
			{
				return this.GetAll<GT_COUNTER>();
			}
		}
		
		public IQueryable<EXTORGACCOUNT> EXTORGACCOUNTs 
		{
			get
			{
				return this.GetAll<EXTORGACCOUNT>();
			}
		}
		
		public IQueryable<DU> DUs 
		{
			get
			{
				return this.GetAll<DU>();
			}
		}
		
		public IQueryable<CCHARSLIST> CCHARSLISTs 
		{
			get
			{
				return this.GetAll<CCHARSLIST>();
			}
		}
		
		public IQueryable<CCHARSABONENTLIST> CCHARSABONENTLISTs 
		{
			get
			{
				return this.GetAll<CCHARSABONENTLIST>();
			}
		}
		
		public IQueryable<ABONENT> ABONENTs 
		{
			get
			{
				return this.GetAll<ABONENT>();
			}
		}
		
		public IQueryable<ABNUF_1> ABNUF_1 
		{
			get
			{
				return this.GetAll<ABNUF_1>();
			}
		}
		
		public IQueryable<GT_LCHARSABONENT> GT_LCHARSABONENTs 
		{
			get
			{
				return this.GetAll<GT_LCHARSABONENT>();
			}
		}
		
		public IQueryable<GT_SALDO_ITOG> GT_SALDO_ITOGs 
		{
			get
			{
				return this.GetAll<GT_SALDO_ITOG>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "Firebird";
			backend.ProviderName = "FirebirdSql.Data.FirebirdClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of AbonentEntitiesModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of AbonentEntitiesModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IAbonentEntitiesModelUnitOfWork : IUnitOfWork
	{
		IQueryable<STREET> STREETs
		{
			get;
		}
		IQueryable<LCHARSLIST> LCHARSLISTs
		{
			get;
		}
		IQueryable<LCHARSABONENTLIST> LCHARSABONENTLISTs
		{
			get;
		}
		IQueryable<HOUSE> HOUSEs
		{
			get;
		}
		IQueryable<GT_COUNTER> GT_COUNTERs
		{
			get;
		}
		IQueryable<EXTORGACCOUNT> EXTORGACCOUNTs
		{
			get;
		}
		IQueryable<DU> DUs
		{
			get;
		}
		IQueryable<CCHARSLIST> CCHARSLISTs
		{
			get;
		}
		IQueryable<CCHARSABONENTLIST> CCHARSABONENTLISTs
		{
			get;
		}
		IQueryable<ABONENT> ABONENTs
		{
			get;
		}
		IQueryable<ABNUF_1> ABNUF_1
		{
			get;
		}
		IQueryable<GT_LCHARSABONENT> GT_LCHARSABONENTs
		{
			get;
		}
		IQueryable<GT_SALDO_ITOG> GT_SALDO_ITOGs
		{
			get;
		}
	}
}
#pragma warning restore 1591
