#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using _027_COKPToVodokanal;

namespace _027_COKPToVodokanal	
{
	public partial class DU
	{
		private int _dU_CD;
		public virtual int DU_CD
		{
			get
			{
				return this._dU_CD;
			}
			set
			{
				this._dU_CD = value;
			}
		}
		
		private string _dU_NM;
		public virtual string DU_NM
		{
			get
			{
				return this._dU_NM;
			}
			set
			{
				this._dU_NM = value;
			}
		}
		
		private string _dU_TEL;
		public virtual string DU_TEL
		{
			get
			{
				return this._dU_TEL;
			}
			set
			{
				this._dU_TEL = value;
			}
		}
		
		private IList<HOUSE> _hOUSEs = new List<HOUSE>();
		public virtual IList<HOUSE> HOUSEs
		{
			get
			{
				return this._hOUSEs;
			}
		}
		
	}
}
#pragma warning restore 1591
