#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace _027_COKPToVodokanal	
{
	public partial class GT_LCHARSABONENT
	{
		private string _lSHET;
		public virtual string LSHET
		{
			get
			{
				return this._lSHET;
			}
			set
			{
				this._lSHET = value;
			}
		}
		
		private int _kODLCHARSLIST;
		public virtual int KODLCHARSLIST
		{
			get
			{
				return this._kODLCHARSLIST;
			}
			set
			{
				this._kODLCHARSLIST = value;
			}
		}
		
		private decimal? _sIGNIFICANCE;
		public virtual decimal? SIGNIFICANCE
		{
			get
			{
				return this._sIGNIFICANCE;
			}
			set
			{
				this._sIGNIFICANCE = value;
			}
		}
		
		private string _lCHARSNAME;
		public virtual string LCHARSNAME
		{
			get
			{
				return this._lCHARSNAME;
			}
			set
			{
				this._lCHARSNAME = value;
			}
		}
		
		private string _sHORTNAME;
		public virtual string SHORTNAME
		{
			get
			{
				return this._sHORTNAME;
			}
			set
			{
				this._sHORTNAME = value;
			}
		}
		
		private string _lOGICSIGNIFICANCE;
		public virtual string LOGICSIGNIFICANCE
		{
			get
			{
				return this._lOGICSIGNIFICANCE;
			}
			set
			{
				this._lOGICSIGNIFICANCE = value;
			}
		}
		
		private DateTime _aBONENTLCHARDATE;
		public virtual DateTime ABONENTLCHARDATE
		{
			get
			{
				return this._aBONENTLCHARDATE;
			}
			set
			{
				this._aBONENTLCHARDATE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
