#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace _027_COKPToVodokanal	
{
	public partial class GT_SALDO_ITOG
	{
		private string _lSHET;
		public virtual string LSHET
		{
			get
			{
				return this._lSHET;
			}
			set
			{
				this._lSHET = value;
			}
		}
		
		private decimal? _bEGSALDO;
		public virtual decimal? BEGSALDO
		{
			get
			{
				return this._bEGSALDO;
			}
			set
			{
				this._bEGSALDO = value;
			}
		}
		
		private decimal? _eNDSALDO;
		public virtual decimal? ENDSALDO
		{
			get
			{
				return this._eNDSALDO;
			}
			set
			{
				this._eNDSALDO = value;
			}
		}
		
		private short _nMONTH;
		public virtual short NMONTH
		{
			get
			{
				return this._nMONTH;
			}
			set
			{
				this._nMONTH = value;
			}
		}
		
		private short _nYEAR;
		public virtual short NYEAR
		{
			get
			{
				return this._nYEAR;
			}
			set
			{
				this._nYEAR = value;
			}
		}
		
		private int _bALANCE_KOD;
		public virtual int BALANCE_KOD
		{
			get
			{
				return this._bALANCE_KOD;
			}
			set
			{
				this._bALANCE_KOD = value;
			}
		}
		
		private string _bALANCENM;
		public virtual string BALANCENM
		{
			get
			{
				return this._bALANCENM;
			}
			set
			{
				this._bALANCENM = value;
			}
		}
		
		private int? _pROVIDERCD;
		public virtual int? PROVIDERCD
		{
			get
			{
				return this._pROVIDERCD;
			}
			set
			{
				this._pROVIDERCD = value;
			}
		}
		
		private decimal? _bEG_DEBET;
		public virtual decimal? BEG_DEBET
		{
			get
			{
				return this._bEG_DEBET;
			}
			set
			{
				this._bEG_DEBET = value;
			}
		}
		
		private decimal? _bEG_KREDIT;
		public virtual decimal? BEG_KREDIT
		{
			get
			{
				return this._bEG_KREDIT;
			}
			set
			{
				this._bEG_KREDIT = value;
			}
		}
		
		private decimal? _eND_DEBET;
		public virtual decimal? END_DEBET
		{
			get
			{
				return this._eND_DEBET;
			}
			set
			{
				this._eND_DEBET = value;
			}
		}
		
		private decimal? _eND_KREDIT;
		public virtual decimal? END_KREDIT
		{
			get
			{
				return this._eND_KREDIT;
			}
			set
			{
				this._eND_KREDIT = value;
			}
		}
		
		private decimal? _fIRST_BEGSALDO;
		public virtual decimal? FIRST_BEGSALDO
		{
			get
			{
				return this._fIRST_BEGSALDO;
			}
			set
			{
				this._fIRST_BEGSALDO = value;
			}
		}
		
		private decimal? _fIRST_BEG_DEBET;
		public virtual decimal? FIRST_BEG_DEBET
		{
			get
			{
				return this._fIRST_BEG_DEBET;
			}
			set
			{
				this._fIRST_BEG_DEBET = value;
			}
		}
		
		private decimal? _fIRST_BEG_KREDIT;
		public virtual decimal? FIRST_BEG_KREDIT
		{
			get
			{
				return this._fIRST_BEG_KREDIT;
			}
			set
			{
				this._fIRST_BEG_KREDIT = value;
			}
		}
		
		private decimal? _lAST_ENDSALDO;
		public virtual decimal? LAST_ENDSALDO
		{
			get
			{
				return this._lAST_ENDSALDO;
			}
			set
			{
				this._lAST_ENDSALDO = value;
			}
		}
		
		private decimal? _lAST_END_DEBET;
		public virtual decimal? LAST_END_DEBET
		{
			get
			{
				return this._lAST_END_DEBET;
			}
			set
			{
				this._lAST_END_DEBET = value;
			}
		}
		
		private decimal? _lAST_END_KREDIT;
		public virtual decimal? LAST_END_KREDIT
		{
			get
			{
				return this._lAST_END_KREDIT;
			}
			set
			{
				this._lAST_END_KREDIT = value;
			}
		}
		
		private int? _rESOURCE_KOD;
		public virtual int? RESOURCE_KOD
		{
			get
			{
				return this._rESOURCE_KOD;
			}
			set
			{
				this._rESOURCE_KOD = value;
			}
		}
		
		private string _rESOURCE_NAME;
		public virtual string RESOURCE_NAME
		{
			get
			{
				return this._rESOURCE_NAME;
			}
			set
			{
				this._rESOURCE_NAME = value;
			}
		}
		
	}
}
#pragma warning restore 1591
