//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18063
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aConverterClassMariaDB {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aConverterClassMariaDB.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на begin;
        ///DROP DATABASE IF EXISTS ConverterDB;
        ///COMMIT;
        ///begin;
        ///create database `ConverterDB`;
        ///USE `converterdb`;
        ///
        ///CREATE TABLE `aaddchar` (
        ///  `ID` int(11) NOT NULL AUTO_INCREMENT,
        ///  `LSHET` varchar(10) DEFAULT NULL,
        ///  `ADDCHARCD` int(11) DEFAULT NULL,
        ///  `VALUE` varchar(30) DEFAULT NULL,
        ///  PRIMARY KEY (`ID`)
        ///);
        ///
        ///
        ///CREATE TABLE `abonent` (
        ///  `ID` int(11) NOT NULL AUTO_INCREMENT,
        ///  `LSHET` varchar(10) DEFAULT NULL,
        ///  `HOUSECD` int(11) DEFAULT NULL,
        ///  `DISTKOD` int(11) DEFAULT NULL,
        ///  `DISTNAME` [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ScriptMariaDB {
            get {
                return ResourceManager.GetString("ScriptMariaDB", resourceCulture);
            }
        }
    }
}
